### ISSUE TITLE
No error on ALOpsAppPublish when using batch_publish_folder

### ISSUE THREAD

**Issue by jcoe-nvt** [HodorNV/ALOps#123]
When batch publish fails, I can see an error in the output, but the pipeline step doesn't fail.
This results in a successful build, so we won't notice that there are actually errors:

![image](https://user-images.githubusercontent.com/49404625/80585528-ca398380-8a13-11ea-9430-9e7b385bb077.png)

**Comment by waldo1001** [comment]
We noticed - will be fixed in next release!  Thanks

**Comment by AdminHodor** [comment]
Dear @jcoe-nvt ,

Fix for this is in version v1.429, which we just released. Could you please validate the solution?

Kind regards,

**Comment by jcoe-nvt** [comment]
Still an error in the publish step and marked as successful. But error has changed, as logic for the batch publish probably changed too?

Previously I needed to copy the apps to a folder in c:/run/devops on the docker container (with own written powershell script) and provide that folder to the "batch_publish_folder" parameter.
Now I see that ALOps looks at folder on the build agent. But i'm not sure how that folder is determined. Can you explain?

![image](https://user-images.githubusercontent.com/49404625/80705836-78622d80-8ae7-11ea-9fff-d285d26ccc34.png)

**Comment by AdminHodor** [comment]
Dear @jcoe-nvt ,

>>But error has changed, as logic for the batch publish probably changed too?
>>Previously I needed to copy the apps to a folder in c:/run/devops on the docker container (with own written powershell script) and provide that folder to the "batch_publish_folder" parameter.
We indeed changed the behavior of this, the folder used is copied on the fly to the docker container which allows users to download/set all Apps in one folder on the host. ALOps will copy it to the container and do processing as before.

We presumed the folder was always available on the host, which apparently is not the case.
Just pushed out a hotfix v1.429.**1380** which allows for both scenarios; if the specied folder is found on the host it is copied to the container, if not found the Task should run as before.
Please not it could take a couple of pipeline runs to pickup the new version.

The pipeline not stopping on an Error is not expected behaviour, we'll have a further look into that.

Kind regards,

**Comment by jcoe-nvt** [comment]
Dear @AdminHodor ,

The pipeline now semi-works as before. I had to change the "batch_publish_folder" to 'Artifacts'. Previously the code looked in the docker container for the folder provided in the "batch_publish_folder" parameter. Now it seems that the code is looking fixed in C:/run/devops/Artifacts'.

'ALOpsPublish' now stops on error when batch publishing.
Thanks for the quick fix.

Kind regards,
Jonas
