### ISSUE TITLE
ALOpsDockerCreate - containerhelperprerelease

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#188]
Just found out the ALOpsDockerCreate was failing with

`The specified module 'BcContainerHelper' with version '1.0.3' was not loaded because no valid module file was found in any module directory.
`

since the module installed was version 1.0.4. Adding containerhelperprerelease: true to the ALOpsDockerCreate steps seemed to fixed it. Is this the adviced setting for ALOpsDockerCreate ?

**Comment by mrabus** [comment]
I just ran into the same issue. Had several pipelines running this morning using the same Artifacts / Image. Is it maybe relaeed to your release a few minutes ago?

**Comment by waldo1001** [comment]
We just did a release, yes - and this is unexpected - my apologies :(.  Investigating...

**Comment by AdminHodor** [comment]
Dear @mrabus , @fvet ,

Appologies for this, is fixed in hotfix release v1.434.1672

Kind regards,

**Comment by mrabus** [comment]
Hello @AdminHodor, @waldo1001, 

I can't confirm that. I have the newest release but the error remains. 

![image](https://user-images.githubusercontent.com/2485163/91460855-a171af80-e888-11ea-940f-991187d8e4ef.png)

**Comment by AdminHodor** [comment]
Hello @mrabus ,

We did encounter the same error on our test-machines right now. We had a fixed version for BcContainerHelper in our code, a premature optimization we did to prevent installation of BcContainerHelper every run.  Just today, BcContainerHelper v1.0.4
was release together with ALOps that made this fail. 

We reworked the code, pulled away from the fixed version and made another mechanism for installing/updating BcContainerhelper. The parameter [containerhelperprerelease] will be removed, and we always work with the Current release of BcContainerHelper. If you do want the Pre-Release, you can install it manually on the build agent and will be picked up by ALOps.

Appologies for the back and forth, please check again if v1.434.1674 fixed this issue for good.

Kind regards,

**Comment by mrabus** [comment]
Hi @AdminHodor,

nope, it unfortunately doesn't solve it buuut we have a new message. 

![image](https://user-images.githubusercontent.com/2485163/91485539-4c936080-e8ab-11ea-824f-3ddf4c351fd1.png)

My pipeline, without prerelease paramater: 
![image](https://user-images.githubusercontent.com/2485163/91485651-72b90080-e8ab-11ea-9e7c-3beeb963966e.png)

Any idea what could be wrong?

**Comment by fvet** [comment]
Same here, without prerelease, running the latest ALOps version.

**Comment by waldo1001** [comment]
Sorry about this - we're having troubles reproducing it .. thanks for reporting this fast!

**Comment by waldo1001** [comment]
New release online - now I can't replicate it anymore in any environment - can you try again?

**Comment by mrabus** [comment]
Looks good, my pipeline managed to create the container - yaaay

**Comment by fvet** [comment]
We are back online too. Thanks!

**Comment by waldo1001** [comment]
That you for reporting - we clearly don't have all scenarios .. and we need reports like this ;-)
