### ISSUE TITLE
batch_publish_folder not respected in ALOpsAppPublish

### ISSUE THREAD

**Issue by kasperdj** [HodorNV/ALOps#246]
**Describe the bug**
I have a task to install the previous verion of my app which is in the a folder in my repo.
When this task is run, the system tries to install/re-install **all apps** in my repo and not only the ones specified in the **batch_publish_folder** parameter causing overhead and longer runtimes in my pipelines!

See screenshot for details:

![image](https://user-images.githubusercontent.com/54669593/97970075-42b53e80-1dc1-11eb-954d-24c6ee2ebc31.png)

**the used yaml**
```yaml
name: $(Build.BuildId)

variables:
- group: AzureKeyVault
- name: 'RunTests'
  value: '0'
- name: 'TestSuite'
  value: 'EV-TEST'
- name: 'CodeAnalyzers'
  value: 'CodeCop,UICop'
- name: 'PublishDependencies'
  value: '0'  

pool:
  name: EV_OnPremise

resources:
  repositories:
    - repository: 'yamltemplates'
      type: 'git'
      name: 'Templates/Templates'
      ref:  'refs/heads/master'

steps:
- checkout: self
  clean: true

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
# EV: Move Unit Tests to Test app if needed
- template: 'OnPrem-Builds/MoveUnitTestToTest.yml@yamltemplates'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
# EV: Copy EVBusinessCentralDevelopmentHelper to Build Agent
- template: 'OnPrem-Builds/CopyEVBCDevHelperToBuildAgent.yml@yamltemplates'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
- task: ALOpsDockerCreate@1
  inputs:
    artifactversion: $(BC_Version)
    artifactcountry: $(BC_Localization)
    artifacttype: $(BC_EnvironmentType)
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
- task: ALOpsDockerStart@1
  inputs:
    docker_pull: false
    accept_image_eula: true
    accept_image_outdated: true
    docker_parameters: '--isolation=hyperv'
    memory_gb: 16  
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsLicenseImport@1
  inputs:
    usedocker: true
    license_path: $(BC_license)
    
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
- task: ALOpsDockerExec@1
  displayName: 'EV: Show Businees Central License Information'
  inputs:
    inline_script: |
      Get-NavServerInstance | Export-NavServerLicenseInformation
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppPublish@1
  displayName: 'ALOps Install AL TestTool'
  condition: and(succeeded(), eq(variables['RunTests'], '1'))
  inputs:
    usedocker: true
    installaltesttool: true
    skip_verification: true
    install_al_app_names: |
     Tests-TestLibraries
     System Application Test
     System Application Test Library
     Any
     Library Assert
     Test Runner
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppPublish@1
  displayName: 'EV: Install ISV and dependencies apps'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    batch_publish_folder: '.\app\Dependencies'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
# EV: Install EVBusinessCentralDevelopmentHelper
- template: 'OnPrem-Builds/InstallEVBCDevHelperInDocker.yml@yamltemplates'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Breaking changes - compare with master
#- task: DownloadBuildArtifacts@0
#  inputs:
#    buildType: 'specific'
#    project: '9f67f062-53be-47a5-bdd7-08a6af20386f'
#    pipeline: '17'
#    buildVersionToDownload: 'latestFromBranch'
#    branchName: 'refs/heads/master'
#    downloadType: 'specific'
#    itemPattern: '**/*APP.app'
#    downloadPath: '$(System.ArtifactsDirectory)'

#- task: ALOpsAppPublish@1
#  displayName: 'ALOps Previous master Publish AL-App'
#  inputs:
#    usedocker: true
#    nav_artifact_app_filter: '*_APP.app'   
#    skip_verification: true    
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppCompiler@1
  displayName: 'ALOps Compile App'
  inputs:
    usedocker: true
    targetproject: 'app/app.json'
    nav_app_version: '?.?.?.*'
    al_analyzer: $(CodeAnalyzers)
    app_file_suffix: '_APP'
    failed_on_warnings: true    
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# EV: Generate Xliff files
- template: 'OnPrem-Builds/GenerateXliffFiles.yml@yamltemplates'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppCompiler@1
  displayName: 'ALOps Re-Compile App with xliff'
  inputs:
    usedocker: true
    targetproject: 'app/app.json'
    nav_app_version: '?.?.?.?'
    app_file_suffix: '_APP'
    failed_on_warnings: true    
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppPublish@1
  displayName: 'EV: Install Previous App Version'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    batch_publish_folder: '.\app\PrevAppVersion'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppPublish@1
  displayName: 'ALOps Publish AL-App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*_APP.app'   
    skip_verification: true 
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppCompiler@1
  displayName: 'ALOps Compile Test App'
  condition: and(succeeded(), eq(variables['RunTests'], '1'))
  inputs:
    usedocker: true
    targetproject: 'Test/app.json'
    nav_app_version: '?.?.?.?'
    app_file_suffix: '_TEST'
    failed_on_warnings: true    
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppPublish@1
  displayName: 'ALOps Publish AL-TEST App'
  condition: and(succeeded(), eq(variables['RunTests'], '1'))
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*_TEST.app'   
    skip_verification: true 
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppTest@1
  displayName: 'EV: Run Custom Tests'
  condition: and(succeeded(), eq(variables['RunTests'], '1'))
  inputs:
    usedocker: true
    import_action: "Skip"
    import_testtoolkit: false
    testpage: '130455'
    testsuite: $(TestSuite) 
    failed_test_action: 'Error'
  continueOnError: true   
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: PublishTestResults@2
  displayName: 'ALOps Publish Test Results **/TestResults.xml'
  condition: and(succeeded(), eq(variables['RunTests'], '1'))
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: '**/TestResults.xml'
    testRunTitle: 'BC Test Results: $(Build.BuildId)'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: PublishBuildArtifacts@1
  displayName: 'Publish App Dependencies'
  condition: and(succeeded(), eq(variables['PublishDependencies'], '1'))
  inputs:
    PathtoPublish: '.\app\Dependencies'
    ArtifactName: 'Dependencies'
    publishLocation: 'Container'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsDockerRemove@1
  displayName: 'ALOps Remove Docker Container'
  enabled: true
  condition: always()
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

**the output**
```
See attached pipeline log
```
[EV_Internal_1600.0.1.2297.txt](https://github.com/HodorNV/ALOps/files/5480395/EV_Internal_1600.0.1.2297.txt)

**Comment by kasperdj** [comment]
Status?

**Comment by waldo1001** [comment]
Hi @kasperdj ,

we are not able to repro this scenario.  We have pipelines which does the exact same thing, and not picking the wrong folder :(.

Can you help me setting this up?

**Comment by kasperdj** [comment]
Here are some additional details - please focus on my comments in the screenshot of the log file where it seams like that the batch_publish_folder parameter is lost during execution.

I can also offer a shadow session if needed - in that case contact me on krj@elbek-vejrup.dk

![image](https://user-images.githubusercontent.com/54669593/98676553-0acb6f80-235c-11eb-979f-4ea9a9fa6624.png)

![image](https://user-images.githubusercontent.com/54669593/98676568-1159e700-235c-11eb-8432-fcfa65ae7877.png)

![image](https://user-images.githubusercontent.com/54669593/98676587-15860480-235c-11eb-9fcd-e0910ffc55e0.png)

![image](https://user-images.githubusercontent.com/54669593/98676612-1d45a900-235c-11eb-9228-f3ea285fcb8a.png)

![image](https://user-images.githubusercontent.com/54669593/98676641-26cf1100-235c-11eb-8064-87dd1190949d.png)

**Comment by waldo1001** [comment]
In your screenshot, you see that the value is the default value.  We already fixed that (to be released soon).
![image](https://user-images.githubusercontent.com/12088142/98989359-4b2c1880-2529-11eb-8e94-676745760deb.png)

What we think happens is that you are influenced by a cleanup that doesn't work properly in DevOps.  We recently noticed this is not enough for business central:
![image](https://user-images.githubusercontent.com/12088142/98989430-626b0600-2529-11eb-83a0-220b1b865070.png)

So, can I suggest the following:
- Edit your pipeline
- click the three dots on the far right, and go to triggers:
![image](https://user-images.githubusercontent.com/12088142/98989680-b70e8100-2529-11eb-84fe-385a5ac1f742.png)
- on the Yaml-tab, click Get Sources, and then change the cleanup options to:
![image](https://user-images.githubusercontent.com/12088142/98989544-92b2a480-2529-11eb-986f-ed7ab14ecdaf.png)

We think there are apps in that folder from a previous pipeline.. and the cleanup didn't happen decently.

In the meantime, i'll keep trying to setup a repro...

**Comment by waldo1001** [comment]
@kasperdj , did you try the above?

**Comment by kasperdj** [comment]
Well it still does not work.
Add this clean up setting to my pipeline:

![image](https://user-images.githubusercontent.com/54669593/100084033-8b08cf00-2e4a-11eb-98e4-48e6902a2781.png)

My yaml is unchanged:

![image](https://user-images.githubusercontent.com/54669593/100084176-bbe90400-2e4a-11eb-9ae6-e60b91209419.png)

But is still forgets to read the **batch_publish_folder parameter** hence all the apps in my repo (artifacts on build agent) is still tried to be re-published again:

![image](https://user-images.githubusercontent.com/54669593/100084380-fce11880-2e4a-11eb-8cab-5f5ca3177461.png)

![image](https://user-images.githubusercontent.com/54669593/100084350-f357b080-2e4a-11eb-998e-3f3b9f280aac.png)

![image](https://user-images.githubusercontent.com/54669593/100084399-04a0bd00-2e4b-11eb-888f-3f0c819986df.png)

**Comment by waldo1001** [comment]
Good news.  We have not been able to repro this .. but we have a lead.  it's because of the mutiple batch-publish steps.

It means we'll have to change around how we decide to install apps - but I think we'll be able to have a fix this week.

**Comment by kasperdj** [comment]
@waldo1001 sound great, thx. for the update

**Comment by waldo1001** [comment]
Hi @kasperdj , did you notice improvement?

**Comment by kasperdj** [comment]
It respects the folder now :-)
Why it takes 6s to do nothing (folder is empty) that we leave as a mistery:

![image](https://user-images.githubusercontent.com/54669593/100621772-5f8d5500-3320-11eb-8a87-18e7eab61f30.png)

**Comment by waldo1001** [comment]
Thanks, @kasperdj ,

It's generic code that loads/unloads libraries - also for folders that don't contain anything ;-).  It's the step that decides that it has to execute something, not the content of the folder.  It's may be an optimization we can do .. 

Previously, it was also looking at the right folder, only we printed the wrong value (defaultvalue in stead of value).  It's the mechanics in the background that have changed...
