### ISSUE TITLE
[error]Batch App-Publish failed: The background process reported an error with the following message: "The named pipe target process has ended.".

### ISSUE THREAD

**Issue by Arthurvdv** [HodorNV/ALOps#619]
**Describe the bug**
With the new release of v1.455.3529 I was eager to start our vNext pipelines and encountered a new error.

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
parameters:
  nav_artifact_app_filter: '*.app'
  batch_publish_folder: '.apps'

steps:
- task: ALOpsAppPublish@1
  displayName: 'Publish Dependencies'
  inputs:
    usedocker: true
    nav_artifact_app_filter: ${{ parameters.nav_artifact_app_filter }}
    batch_publish_folder: ${{ parameters.batch_publish_folder }}
    skip_verification: true
    blocksymbolsonly: true
```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
2023-03-21T17:47:55.2398322Z ##[section]Starting: Publish Dependencies
2023-03-21T17:47:55.2708617Z ==============================================================================
2023-03-21T17:47:55.2708886Z Task         : ALOps App Publish
2023-03-21T17:47:55.2709098Z Description  : Publish AL Extension to Business Central
2023-03-21T17:47:55.2709296Z Version      : 1.455.3529
2023-03-21T17:47:55.2709450Z Author       : Hodor
2023-03-21T17:47:55.2709663Z Help         : Publish Business Central extension to service tier.
2023-03-21T17:47:55.2709936Z ==============================================================================
2023-03-21T17:47:56.1427171Z *** Validate configuration
2023-03-21T17:47:56.1858449Z *** Task Inputs:
2023-03-21T17:47:56.1899688Z 
2023-03-21T17:47:56.1981651Z name                                                                                                              value
2023-03-21T17:47:56.1983191Z ----                                                                                                              -----
2023-03-21T17:47:56.1983797Z usedocker                                                                                                          True
2023-03-21T17:47:56.1984160Z fixed_tag                                                                                                              
2023-03-21T17:47:56.1984589Z installpublishedapps                                                                                               True
2023-03-21T17:47:56.1984890Z installaltesttool                                                                                                 False
2023-03-21T17:47:56.1985333Z install_al_app_names                                                                             Tests-TestLibraries...
2023-03-21T17:47:56.1985652Z strictappnames                                                                                                    False
2023-03-21T17:47:56.1986045Z nav_serverinstance                                                                                                BC140
2023-03-21T17:47:56.1986751Z artifact_path                                                                                                          
2023-03-21T17:47:56.1987425Z nav_artifact_app_filter                                                                                           *.app
2023-03-21T17:47:56.1987972Z skip_verification                                                                                                  True
2023-03-21T17:47:56.1988962Z forceinstall                                                                                                      False
2023-03-21T17:47:56.1989356Z forcesync                                                                                                         False
2023-03-21T17:47:56.1990032Z publish_scope                                                                                                    Global
2023-03-21T17:47:56.1990457Z tenant                                                                                                          default
2023-03-21T17:47:56.1991626Z batch_publish_folder                                                                                              .apps
2023-03-21T17:47:56.1992028Z publisherazureactivedirectorytenantid                                                                                  
2023-03-21T17:47:56.1992343Z blocksymbolsonly                                                                                                   True
2023-03-21T17:47:56.1992470Z 
2023-03-21T17:47:56.2015973Z 
2023-03-21T17:47:56.2022643Z 
2023-03-21T17:47:56.2163988Z *** For documentation, please visit   : https://www.alops.be/documentation
2023-03-21T17:47:56.2167378Z 
2023-03-21T17:47:56.6309487Z *** ALOps License:
2023-03-21T17:47:56.6326667Z   * Licensed To: Van Roey (Collection License)
2023-03-21T17:47:56.6329862Z 
2023-03-21T17:47:56.6422155Z *** Importing required PS-Functions
2023-03-21T17:47:56.8793906Z *** Initiate Docker Session
2023-03-21T17:47:57.1167016Z *** Set Docker Container ErrorActionPreference = Stop
2023-03-21T17:47:57.3535930Z *** Start Batch App-Publish.
2023-03-21T17:47:57.4163603Z *** Copy Artifacts: [C:\azure-vsts-agent-build\_work\466\s\.apps] to [c:\Run\DevOps\Artifacts-5fdf1f9088314e91a9f593c2e6821fbe]
2023-03-21T17:47:58.3854799Z *** Import NAV/BC Management DLL's
2023-03-21T17:47:58.3884304Z *** Loading assemblies for ServiceTier [BC].
2023-03-21T17:47:58.6548225Z *** Loading assemblies from: [C:\program files\microsoft dynamics nav\220\service]
2023-03-21T17:47:58.7022742Z *** Selected module: [C:\program files\microsoft dynamics nav\220\service\Management\Microsoft.Dynamics.Nav.Management.dll]
2023-03-21T17:47:58.7042006Z *** Loading module: [C:\program files\microsoft dynamics nav\220\service\Management\Microsoft.Dynamics.Nav.Management.dll]
2023-03-21T17:47:58.7671030Z *** Selected module: [C:\program files\microsoft dynamics nav\220\service\Management\Microsoft.Dynamics.Nav.Apps.Management.dll]
2023-03-21T17:47:58.7672795Z *** Loading module: [C:\program files\microsoft dynamics nav\220\service\Management\Microsoft.Dynamics.Nav.Apps.Management.dll]
2023-03-21T17:47:58.9503355Z *** Get Available Applications from [c:\Run\DevOps\Artifacts-5fdf1f9088314e91a9f593c2e6821fbe].
2023-03-21T17:47:58.9591887Z *** Get [*.app] files recursive from [c:\Run\DevOps\Artifacts-5fdf1f9088314e91a9f593c2e6821fbe]
2023-03-21T17:47:58.9631145Z *** Found [6] files.
2023-03-21T17:47:58.9638057Z *** Extract App detail from [C:\Run\DevOps\Artifacts-5fdf1f9088314e91a9f593c2e6821fbe\<depedency_app1>.app]
2023-03-21T17:47:59.1333328Z *** Extract App detail from [C:\Run\DevOps\Artifacts-5fdf1f9088314e91a9f593c2e6821fbe\<depedency_app2>.app]
2023-03-21T17:47:59.1421600Z *** Extract App detail from [C:\Run\DevOps\Artifacts-5fdf1f9088314e91a9f593c2e6821fbe\<depedency_app3>.app]
2023-03-21T17:47:59.1449186Z *** Extract App detail from [C:\Run\DevOps\Artifacts-5fdf1f9088314e91a9f593c2e6821fbe\<depedency_app4>.app]
2023-03-21T17:47:59.1483350Z *** Extract App detail from [C:\Run\DevOps\Artifacts-5fdf1f9088314e91a9f593c2e6821fbe\<depedency_app5>.app]
2023-03-21T17:47:59.1507622Z *** Extract App detail from [C:\Run\DevOps\Artifacts-5fdf1f9088314e91a9f593c2e6821fbe\<depedency_app6>.app]
2023-03-21T17:47:59.1583939Z *** Remove duplicate Apps
2023-03-21T17:47:59.1817553Z *** Installing Applications:
2023-03-21T17:47:59.2108625Z 
2023-03-21T17:47:59.2142753Z **************************************
2023-03-21T17:47:59.2146018Z  * App File = [C:\Run\DevOps\Artifacts-5fdf1f9088314e91a9f593c2e6821fbe\<depedency_app1>.app]
2023-03-21T17:47:59.2147018Z 
2023-03-21T17:47:59.2209020Z  * App.ID        = <redacted>
2023-03-21T17:47:59.2211540Z  * App.Name      = <redacted>
2023-03-21T17:47:59.2216329Z  * App.Publisher = <redacted>
2023-03-21T17:47:59.2245319Z  * App.Version   = 19.0.58872.0
2023-03-21T17:47:59.2502438Z *** Loading assemblies from: [C:\program files\microsoft dynamics nav\220\service]
2023-03-21T17:47:59.2563872Z *** Loading: [C:\program files\microsoft dynamics nav\220\service\Microsoft.Dynamics.Nav.CodeAnalysis.dll]
2023-03-21T17:47:59.2977904Z *** Load Dependency: C:\program files\microsoft dynamics nav\220\service\System.Runtime.Caching.dll
2023-03-21T17:48:11.6241900Z The background process reported an error with the following message: "The named pipe target process has ended.".
2023-03-21T17:48:11.6242476Z At C:\azure-vsts-agent-build\_work\_tasks\ALOpsAppPublish_c004e2d2-e842-40f0-9ed4-89fb9bdd2e33\1.455.3529\69dd16c8-b3ce
2023-03-21T17:48:11.6242890Z -49ef-a2f6-2b05524a6386.ps1:156 char:17
2023-03-21T17:48:11.6243239Z + ...             $Result = Invoke-Command -Session $DockerSession -ScriptB ...
2023-03-21T17:48:11.6244972Z +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-03-21T17:48:11.6245651Z     + CategoryInfo          : OperationStopped: (c6e9fd48202ae75...227aaae455547ab:String) [], PSRemotingTransportExce 
2023-03-21T17:48:11.6246054Z    ption
2023-03-21T17:48:11.6246290Z     + FullyQualifiedErrorId : JobFailure
2023-03-21T17:48:11.6246505Z  
2023-03-21T17:48:11.6246577Z 
2023-03-21T17:48:11.6262936Z ##[error]Batch App-Publish failed: The background process reported an error with the following message: "The named pipe target process has ended.".
2023-03-21T17:48:11.6548577Z ##[section]Async Command Start: Add Build Tag
2023-03-21T17:48:11.6549219Z Build '80008' has following tags now: AL.Analyzer.PerTenantExtensionCop, AL.Analyzer.CodeCop, AL.Analyzer.UICop, App.Common Data.19.0.58872.0, BC.Platform.22.0.54318.0, myimage-sandbox-22.0.54348.0-be-10.0.20348.1249-ltsc2022, BC.Version.22.0.54348.0
2023-03-21T17:48:11.6549706Z ##[section]Async Command End: Add Build Tag
2023-03-21T17:48:11.6550602Z ##[section]Finishing: Publish Dependencies
```

**Screenshots**
![image](https://user-images.githubusercontent.com/44637996/226709026-4398ab01-a965-4e3a-8cea-b6bc16fe5a7b.png)

**Comment by AdminHodor** [comment]
Dear @Arthurvdv , @TheDoubleH ,

We just released a hotfix (v1.455.3559) which should solve the Assembly-Reference issue in all tasks.
Please let us know if this release works for you.

Kind regards,

**Comment by Arthurvdv** [comment]
Resolved with https://github.com/HodorNV/ALOps/issues/621

**Comment by Arthurvdv** [comment]
Oops, closed this issue to soon, the same error is still here.

**Comment by Arthurvdv** [comment]
Unfortunately still the same error it seems

```
2023-03-23T09:12:38.4429963Z ##[section]Starting: Publish Dependencies
2023-03-23T09:12:38.4662070Z ==============================================================================
2023-03-23T09:12:38.4662290Z Task         : ALOps App Publish
2023-03-23T09:12:38.4662471Z Description  : Publish AL Extension to Business Central
2023-03-23T09:12:38.4662632Z Version      : 1.455.3571
2023-03-23T09:12:38.4662758Z Author       : Hodor
2023-03-23T09:12:38.4662934Z Help         : Publish Business Central extension to service tier.
2023-03-23T09:12:38.4663153Z ==============================================================================
2023-03-23T09:12:39.1369217Z *** Validate configuration
2023-03-23T09:12:39.1745013Z *** Task Inputs:
2023-03-23T09:12:39.1779207Z 
2023-03-23T09:12:39.2209086Z name                                                                                                              value
2023-03-23T09:12:39.2209424Z ----                                                                                                              -----
2023-03-23T09:12:39.2209952Z usedocker                                                                                                          True
2023-03-23T09:12:39.2210754Z fixed_tag                                                                                                              
2023-03-23T09:12:39.2211417Z installpublishedapps                                                                                               True
2023-03-23T09:12:39.2211911Z installaltesttool                                                                                                 False
2023-03-23T09:12:39.2212731Z install_al_app_names                                                                             Tests-TestLibraries...
2023-03-23T09:12:39.2213094Z strictappnames                                                                                                    False
2023-03-23T09:12:39.2214153Z nav_serverinstance                                                                                                BC140
2023-03-23T09:12:39.2214628Z artifact_path                                                                                                          
2023-03-23T09:12:39.2215472Z nav_artifact_app_filter                                                                                           *.app
2023-03-23T09:12:39.2216472Z skip_verification                                                                                                  True
2023-03-23T09:12:39.2218129Z forceinstall                                                                                                      False
2023-03-23T09:12:39.2218588Z forcesync                                                                                                         False
2023-03-23T09:12:39.2218975Z publish_scope                                                                                                    Global
2023-03-23T09:12:39.2219238Z tenant                                                                                                          default
2023-03-23T09:12:39.2220577Z batch_publish_folder                                                                                              .apps
2023-03-23T09:12:39.2220876Z publisherazureactivedirectorytenantid                                                                                  
2023-03-23T09:12:39.2221932Z blocksymbolsonly                                                                                                   True
2023-03-23T09:12:39.2222126Z 
2023-03-23T09:12:39.2237745Z 
2023-03-23T09:12:39.2244868Z 
2023-03-23T09:12:39.2362855Z *** For documentation, please visit   : https://www.alops.be/documentation
2023-03-23T09:12:39.2364438Z 
2023-03-23T09:12:39.6462892Z *** ALOps License:
2023-03-23T09:12:39.6475179Z   * Licensed To: Van Roey (Collection License)
2023-03-23T09:12:39.6477675Z 
2023-03-23T09:12:39.6545818Z *** Importing required PS-Functions
2023-03-23T09:12:39.8269326Z *** Initiate Docker Session
2023-03-23T09:12:40.0466559Z *** Set Docker Container ErrorActionPreference = Stop
2023-03-23T09:12:40.2242431Z *** Start Batch App-Publish.
2023-03-23T09:12:40.2816462Z *** Copy Artifacts: [C:\azure-vsts-agent-build\_work\39\s\.apps] to [c:\Run\DevOps\Artifacts-5b2b1adb708848dcbc631cfab9349b37]
2023-03-23T09:12:41.1005540Z *** Import NAV/BC Management DLL's [False]
2023-03-23T09:12:41.1027683Z *** Loading assemblies for ServiceTier [BC].
2023-03-23T09:12:41.3149219Z *** Loading assemblies from: [C:\program files\microsoft dynamics nav\220\service]
2023-03-23T09:12:41.3617883Z *** Selected module: [C:\program files\microsoft dynamics nav\220\service\Management\Microsoft.Dynamics.Nav.Management.dll]
2023-03-23T09:12:41.3625739Z *** Loading module: [C:\program files\microsoft dynamics nav\220\service\Management\Microsoft.Dynamics.Nav.Management.dll]
2023-03-23T09:12:41.3788345Z *** Load Dependency: C:\program files\microsoft dynamics nav\220\service\Management\Microsoft.Dynamics.Nav.Management.dll
2023-03-23T09:12:41.4380224Z *** Selected module: [C:\program files\microsoft dynamics nav\220\service\Management\Microsoft.Dynamics.Nav.Apps.Management.dll]
2023-03-23T09:12:41.4382683Z *** Loading module: [C:\program files\microsoft dynamics nav\220\service\Management\Microsoft.Dynamics.Nav.Apps.Management.dll]
2023-03-23T09:12:41.4413971Z *** Load Dependency: C:\program files\microsoft dynamics nav\220\service\Management\Microsoft.Dynamics.Nav.Apps.Management.dll
2023-03-23T09:12:41.5827186Z *** Get Available Applications from [c:\Run\DevOps\Artifacts-5b2b1adb708848dcbc631cfab9349b37].
2023-03-23T09:12:41.5899083Z *** Get [*.app] files recursive from [c:\Run\DevOps\Artifacts-5b2b1adb708848dcbc631cfab9349b37]
2023-03-23T09:12:41.5929348Z *** Found [6] files.
2023-03-23T09:12:41.5937627Z *** Extract App detail from [C:\Run\DevOps\Artifacts-5b2b1adb708848dcbc631cfab9349b37\<depedency_app1>.app]
2023-03-23T09:12:41.7284260Z *** Extract App detail from [C:\Run\DevOps\Artifacts-5b2b1adb708848dcbc631cfab9349b37\<depedency_app2>.app]
2023-03-23T09:12:41.7354234Z *** Extract App detail from [C:\Run\DevOps\Artifacts-5b2b1adb708848dcbc631cfab9349b37\<depedency_app3>.app]
2023-03-23T09:12:41.7378777Z *** Extract App detail from [C:\Run\DevOps\Artifacts-5b2b1adb708848dcbc631cfab9349b37\<depedency_app4>.app]
2023-03-23T09:12:41.7404127Z *** Extract App detail from [C:\Run\DevOps\Artifacts-5b2b1adb708848dcbc631cfab9349b37\<depedency_app5>.app]
2023-03-23T09:12:41.7425363Z *** Extract App detail from [C:\Run\DevOps\Artifacts-5b2b1adb708848dcbc631cfab9349b37\<depedency_app6>.app]
2023-03-23T09:12:41.7480929Z *** Remove duplicate Apps
2023-03-23T09:12:41.7695342Z *** Installing Applications:
2023-03-23T09:12:41.8038945Z 
2023-03-23T09:12:41.8063907Z **************************************
2023-03-23T09:12:41.8067007Z  * App File = [C:\Run\DevOps\Artifacts-5b2b1adb708848dcbc631cfab9349b37\<depedency_app1>.app]
2023-03-23T09:12:41.8070246Z 
2023-03-23T09:12:41.8110603Z  * App.ID        = <redacted>
2023-03-23T09:12:41.8115686Z  * App.Name      = <redacted>
2023-03-23T09:12:41.8120843Z  * App.Publisher = <redacted>
2023-03-23T09:12:41.8134972Z  * App.Version   = 19.0.58872.0
2023-03-23T09:12:41.8350750Z *** Loading assemblies from: [C:\program files\microsoft dynamics nav\220\service]
2023-03-23T09:12:41.8351148Z *** Loading: [C:\program files\microsoft dynamics nav\220\service\Microsoft.Dynamics.Nav.CodeAnalysis.dll]
2023-03-23T09:12:41.8623444Z *** Load Dependency: C:\program files\microsoft dynamics nav\220\service\System.Runtime.Caching.dll
2023-03-23T09:12:44.6544332Z The background process reported an error with the following message: "The named pipe target process has ended.".
2023-03-23T09:12:44.6546109Z At C:\azure-vsts-agent-build\_work\_tasks\ALOpsAppPublish_c004e2d2-e842-40f0-9ed4-89fb9bdd2e33\1.455.3571\a7922655-92ff
2023-03-23T09:12:44.6546634Z -4f15-89dc-a5567cb5b9ca.ps1:156 char:17
2023-03-23T09:12:44.6547081Z + ...             $Result = Invoke-Command -Session $DockerSession -ScriptB ...
2023-03-23T09:12:44.6547531Z +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-03-23T09:12:44.6547934Z     + CategoryInfo          : OperationStopped: (0447816512c43d6...07d8d6edba9cadb:String) [], PSRemotingTransportExce 
2023-03-23T09:12:44.6548627Z    ption
2023-03-23T09:12:44.6549050Z     + FullyQualifiedErrorId : JobFailure
2023-03-23T09:12:44.6549225Z  
2023-03-23T09:12:44.6549286Z 
2023-03-23T09:12:44.6565217Z ##[error]Batch App-Publish failed: The background process reported an error with the following message: "The named pipe target process has ended.".
2023-03-23T09:12:44.6828626Z ##[section]Async Command Start: Add Build Tag
2023-03-23T09:12:44.6829166Z Build '80216' has following tags now: AL.Analyzer.PerTenantExtensionCop, AL.Analyzer.CodeCop, AL.Analyzer.UICop, App.Common Data.19.0.58872.0, BC.Platform.22.0.54512.0, BC.Version.22.0.54157.54570, myimage-sandbox-22.0.54157.54570-be-10.0.20348.1129-ltsc2022
2023-03-23T09:12:44.6829606Z ##[section]Async Command End: Add Build Tag
2023-03-23T09:12:44.6830327Z ##[section]Finishing: Publish Dependencies
```

**Comment by AdminHodor** [comment]
Dear @Arthurvdv,

Thanks for the log, we are able to replicate this based on your parameter.
The issue seems with the 'blocksymbolsonly' parameter.

We'll get on it and provide a fix/feedback asap.

Kind regards,

**Comment by AdminHodor** [comment]
Dear @Arthurvdv ,

Thanks for your patience, could you please try v1.455.3577. We fixed the Sideloading assemblies for the blocksymbolsonly check.

Kind regards,

**Comment by Arthurvdv** [comment]
Issue resolved, thanks! :-)
