### ISSUE TITLE
[error]Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by Arthurvdv** [HodorNV/ALOps#620]
**Describe the bug**
With the new release of v1.455.3529 I was eager to start our vNext pipelines and encountered a new error.

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
  parameters:
   test_suite: 'DEFAULT'

  steps:
  - task: ALOpsAppTest@1
    displayName: 'Run Test Suite'
    inputs:
      usedocker: true
      import_action: "Skip"
      import_testtoolkit: false
      testpage: '130455'
      testsuite: ${{ parameters.test_suite }}
      failed_test_action: 'Error'
    continueOnError: false
```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
2023-03-21T17:43:40.5633892Z ##[section]Starting: Run Test Suite
2023-03-21T17:43:40.5892842Z ==============================================================================
2023-03-21T17:43:40.5893094Z Task         : ALOps App Test
2023-03-21T17:43:40.5893420Z Description  : Run AL-TestSuite for Business Central
2023-03-21T17:43:40.5893627Z Version      : 1.455.3529
2023-03-21T17:43:40.5893774Z Author       : Hodor
2023-03-21T17:43:40.5893971Z Help         : Run Business Central Test-Suite and collect results.
2023-03-21T17:43:40.5894238Z ==============================================================================
2023-03-21T17:43:41.4833047Z *** Validate configuration
2023-03-21T17:43:41.5297591Z *** Task Inputs:
2023-03-21T17:43:41.5338378Z 
2023-03-21T17:43:41.5422757Z name                           value
2023-03-21T17:43:41.5424789Z ----                           -----
2023-03-21T17:43:41.5426959Z usedocker                       True
2023-03-21T17:43:41.5429808Z fixed_tag                           
2023-03-21T17:43:41.5431043Z nav_serverinstance             BC140
2023-03-21T17:43:41.5431488Z tenant                       default
2023-03-21T17:43:41.5432557Z companyname                         
2023-03-21T17:43:41.5432960Z profile                             
2023-03-21T17:43:41.5433197Z bc_username                         
2023-03-21T17:43:41.5434319Z bc_password                         
2023-03-21T17:43:41.5434861Z bc_authentication    NavUserPassword
2023-03-21T17:43:41.5435124Z bc_webclient_url                    
2023-03-21T17:43:41.5435354Z testfilter                          
2023-03-21T17:43:41.5436812Z disabledtests                       
2023-03-21T17:43:41.5437242Z show_available_tests            True
2023-03-21T17:43:41.5437485Z import_testtoolkit             False
2023-03-21T17:43:41.5438754Z import_action                   Skip
2023-03-21T17:43:41.5439110Z testpage                      130455
2023-03-21T17:43:41.5439365Z testsuite                    DEFAULT
2023-03-21T17:43:41.5439671Z extensionid                         
2023-03-21T17:43:41.5440002Z installaltesttool              False
2023-03-21T17:43:41.5440669Z failed_test_action             Error
2023-03-21T17:43:41.5441007Z override_finsql_path                
2023-03-21T17:43:41.5441597Z resultfilename       TestResults.xml
2023-03-21T17:43:41.5442075Z testrunnercodeunitid                
2023-03-21T17:43:41.5442192Z 
2023-03-21T17:43:41.5458556Z 
2023-03-21T17:43:41.5465296Z 
2023-03-21T17:43:41.5588301Z *** For documentation, please visit   : https://www.alops.be/documentation
2023-03-21T17:43:41.5591377Z 
2023-03-21T17:43:41.9857073Z *** ALOps License:
2023-03-21T17:43:41.9918207Z   * Licensed To: Van Roey (Collection License)
2023-03-21T17:43:41.9921650Z 
2023-03-21T17:43:42.0013942Z *** Importing required PS-Functions
2023-03-21T17:43:42.0745382Z *** Working folder: C:\azure-vsts-agent-build\_work\455\s
2023-03-21T17:43:42.0748790Z ***
2023-03-21T17:43:42.0752231Z *** Prepare Docker Session
2023-03-21T17:43:42.1960565Z *** Connect Docker Session
2023-03-21T17:43:42.2030190Z *** Initiate Docker Session
2023-03-21T17:43:42.4644261Z *** Set Docker Container ErrorActionPreference = Stop
2023-03-21T17:43:42.6954007Z *** Copy Modules to Docker
2023-03-21T17:43:44.4775144Z *** Setup Docker Session
2023-03-21T17:43:44.5061402Z *** Checking for container-specific Test Assemblies
2023-03-21T17:43:44.5063760Z *** Using container-specific Test Assemblies
2023-03-21T17:43:44.6357291Z *** Import Modules in Docker Session
2023-03-21T17:43:44.6937799Z *** Import UI Client [C:\Run\DevOps\BCAppTest\bin\Microsoft.Dynamics.Framework.UI.Client.dll]
2023-03-21T17:43:44.6946000Z VERBOSE: Loading module from path 'C:\Run\DevOps\BCAppTest\bin\Microsoft.Dynamics.Framework.UI.Client.dll'.
2023-03-21T17:43:44.9407644Z *** Import NewtonSoft JSON [C:\Program Files\Microsoft Dynamics NAV\220\Service\Newtonsoft.Json.dll]
2023-03-21T17:43:45.0671959Z ##[error]Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
2023-03-21T17:43:45.0957058Z ##[section]Finishing: Run Test Suite
```

**Screenshots**
![image](https://user-images.githubusercontent.com/44637996/226710286-ce407812-5f0e-4e79-81c0-bc18bbb15815.png)

**Comment by AdminHodor** [comment]
Dear @Arthurvdv , @TheDoubleH ,

We just released a hotfix (v1.455.3559) which should solve the Assembly-Reference issue in all tasks.
Please let us know if this release works for you.

Kind regards,

**Comment by acjdekorte** [comment]
Dear @AdminHodor 

Unfortunately this is still not working 
![image](https://user-images.githubusercontent.com/36184654/226903361-60464868-243e-4710-93f0-6fa94db42e9e.png)
![image](https://user-images.githubusercontent.com/36184654/226903493-9c558983-3255-46e3-b545-1618b049d4b2.png)

**Comment by acjdekorte** [comment]
@Arthurvdv Unfortunately this issue is still giving problems

**Comment by AdminHodor** [comment]
Please try our latest release v1.455.3571.

Kind regards,

**Comment by AdminHodor** [comment]
Dear @acjdekorte,

Please try v1.455.3577, edge cases should be solved in this one.

Kind regards,
