### ISSUE TITLE
AlOpsDockerWait timeout

### ISSUE THREAD

**Issue by deano808** [HodorNV/ALOps#695]
The build pipeline is stopped due to hitting the maximum time. The AlOpsDockerStart task has actually failed but the task reports Docker Start OK. The AlOPsDockerWait is waiting for the 'Ready For Connections' in the log which will never appear.

**the used yaml**
```yaml
name: $(Build.BuildId)

trigger:
  batch: true
  branches:
    include:
      - '*'
    exclude:
      - master

variables:
- group: Licence
- name: AppVersion
  value: '21.0.[yyyyWW].*'

stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: AlOpsWebinar

    steps:
    - checkout: self
      clean: true

    - task: DownloadBuildArtifacts@0
      displayName: 'Download Dependant app'
      inputs:
        buildType: 'specific'
        project: '2f54a417-ff17-4fa7-a70d-618f234adb6a'
        pipeline: '3932'
        buildVersionToDownload: 'latestFromBranch'
        allowPartiallySucceededBuilds: true
        branchName: 'refs/heads/master'
        downloadType: 'specific'
        itemPattern: '**/*APP.app'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: DownloadBuildArtifacts@0
      displayName: 'Download Dependant app'
      inputs:
        buildType: 'specific'
        project: '2f54a417-ff17-4fa7-a70d-618f234adb6a'
        pipeline: '3934'
        buildVersionToDownload: 'latestFromBranch'
        allowPartiallySucceededBuilds: true
        branchName: 'refs/heads/master'
        downloadType: 'specific'
        itemPattern: '**/*APP.app'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: PowerShell@2
      displayName: 'Download Deployable Dependant app'
      inputs:
        targetType: 'inline'
        script: 'Invoke-WebRequest -Uri "<REMOVED_URI>'

    - task: PowerShell@2
      displayName: 'Download Deployable Dependant app'
      inputs:
        targetType: 'inline'
        script: 'Invoke-WebRequest -Uri "<REMOVED_URI>"'

    - task: ALOpsAppCompiler@2
      displayName: 'Compile Extension app'
      inputs:
        artifactversion: '21.0'
        artifacttype: 'Sandbox'
        artifactcountry: 'gb'
        alsourcepath: 'app/app.json'
        appversiontemplate: '$(AppVersion)'
        appfilenametemplate: '%APP_PUBLISHER%_%APP_NAME%_%APP_VERSION%_APP.app'
        alcodeanalyzer: 'CodeCop,UICop,PerTenantExtensionCop'

    - task: ALOpsAppCompiler@2
      displayName: 'Compile Test app'
      inputs:
        artifactversion: '21.0'
        artifacttype: 'Sandbox'
        artifactcountry: 'gb'
        alsourcepath: 'test/app.json'
        appversiontemplate: '$(AppVersion)'
        appfilenametemplate: '%APP_PUBLISHER%_%APP_NAME%_%APP_VERSION%_TEST.app'
        alcodeanalyzer: 'CodeCop,UICop,PerTenantExtensionCop'

    - task: ALOpsDockerCreate@1
      displayName: 'ALOPS - Create Docker Image'
      inputs:
        artifactversion: '21.0'
        artifacttype: 'Sandbox'
        artifactcountry: 'gb'

    - task: ALOpsDockerStart@1
      inputs:
        docker_image: '$(ALOPS_BC_IMAGE)'
        memory_gb: 8
        docker_parameters: --isolation=hyperv

    - task: ALOpsDockerWait@1
      inputs:
        search_string: 'Ready for connections!'

    - task: ALOpsLicenseImport@1
      displayName: 'ALOps License Import'
      inputs:
        usedocker: true
        license_path: '$(dev_licence)'

    - task: ALOpsAppPublish@1
      displayName: 'ALOps Install AL TestTool'
      inputs:
        usedocker: true
        installaltesttool: true
        skip_verification: true
        install_al_app_names: |
          System Application Test Library
          Any
          Library Assert
          Tests-TestLibraries
          System Application Test
          Test Runner
          Permissions Mock

    - task: ALOpsAppPublish@1
      displayName: 'ALOps Publish APP Extension'
      inputs:
        usedocker: true
        nav_artifact_app_filter: '*APP.app'
        batch_publish_folder: '$(System.ArtifactsDirectory)'

    - task: ALOpsAppPublish@1
      displayName: 'ALOps Publish TEST Extension'
      inputs:
        usedocker: true
        nav_artifact_app_filter: '*TEST.app'
        skip_verification: true   

    - task: ALOpsAppTest@1
      displayName: 'ALOps Run TestSuite'
      inputs:
        usedocker: true
        import_testtoolkit: false
        import_action: 'Skip'
        testpage: '130455'
        testsuite: 'TECMAN'
        failed_test_action: 'Ignore'
      continueOnError: true   

    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/TestResults.xml'
      inputs:
        testResultsFormat: XUnit
        testResultsFiles: '**/TestResults.xml'
        testRunTitle: 'BC Test Results: $(Build.BuildId)'

    - task: ALOpsDockerRemove@1
      displayName: 'ALOps Remove Docker Container'
      enabled: true
      condition: always()
```

**the output**
```
2023-11-09T17:05:22.5921076Z ##[section]Starting: Job
2023-11-09T17:05:22.8737429Z ##[section]Starting: Initialize job
2023-11-09T17:05:22.8742081Z Agent name: 'ALOpsVM1_3'
2023-11-09T17:05:22.8742620Z Agent machine name: 'ALOPSVM1'
2023-11-09T17:05:22.8742853Z Current agent version: '3.227.1'
2023-11-09T17:05:22.8770702Z Agent running as: 'ALOPSVM1$'
2023-11-09T17:05:22.8893761Z Prepare build directory.
2023-11-09T17:05:22.9495489Z Set build variables.
2023-11-09T17:05:22.9537166Z Download all required tasks.
2023-11-09T17:05:23.0199118Z Checking job knob settings.
2023-11-09T17:05:23.0218388Z    Knob: DockerActionRetries = true Source: $(VSTSAGENT_DOCKER_ACTION_RETRIES) 
2023-11-09T17:05:23.0222917Z    Knob: AgentEnablePipelineArtifactLargeChunkSize = true Source: $(AGENT_ENABLE_PIPELINEARTIFACT_LARGE_CHUNK_SIZE) 
2023-11-09T17:05:23.0225714Z    Knob: ContinueAfterCancelProcessTreeKillAttempt = true Source: $(VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT) 
2023-11-09T17:05:23.0227391Z    Knob: ProcessHandlerTelemetry = true Source: $(AZP_75787_ENABLE_COLLECT) 
2023-11-09T17:05:23.0228802Z    Knob: IgnoreVSTSTaskLib = true Source: $(AZP_AGENT_IGNORE_VSTSTASKLIB) 
2023-11-09T17:05:23.0229135Z Finished checking job knob settings.
2023-11-09T17:05:23.1119383Z Start tracking orphan processes.
2023-11-09T17:05:23.1293312Z ##[section]Finishing: Initialize job
2023-11-09T17:05:23.1569577Z ##[section]Async Command Start: DetectDockerContainer
2023-11-09T17:05:23.1569830Z ##[section]Async Command End: DetectDockerContainer
2023-11-09T17:05:23.1570796Z ##[section]Async Command Start: DetectDockerContainer
2023-11-09T17:05:23.1571170Z ##[section]Async Command End: DetectDockerContainer
2023-11-09T17:05:23.1815873Z ##[section]Starting: Checkout Tecman.AFU001.ReportPack@feature to s
2023-11-09T17:05:23.2885967Z ==============================================================================
2023-11-09T17:05:23.2886750Z Task         : Get sources
2023-11-09T17:05:23.2887136Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2023-11-09T17:05:23.2887326Z Version      : 1.0.0
2023-11-09T17:05:23.2887885Z Author       : Microsoft
2023-11-09T17:05:23.2888475Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
2023-11-09T17:05:23.2888648Z 

<REMOVED_SUCCESS_TASKS_AS_BODY_TOO_LONG_WARNING>

==============================================================================
2023-11-09T17:07:09.2359261Z Task         : ALOps Docker Create
2023-11-09T17:07:09.2359336Z Description  : Create Docker image from Business Central Artifacts
2023-11-09T17:07:09.2359446Z Version      : 1.459.5009
2023-11-09T17:07:09.2359510Z Author       : Hodor
2023-11-09T17:07:09.2359584Z Help         : Create Docker image based on NAV/BC Artifacts.
2023-11-09T17:07:09.2359658Z ==============================================================================
2023-11-09T17:07:10.6784870Z *** Validate configuration
2023-11-09T17:07:10.8724274Z *** Task Inputs:
2023-11-09T17:07:10.8731232Z 
2023-11-09T17:07:10.9243465Z name                      value                                                                                      
2023-11-09T17:07:10.9246953Z ----                      -----                                                                                      
2023-11-09T17:07:10.9248358Z artifactspecification     Specific                                                                                   
2023-11-09T17:07:10.9253315Z artifactversion           21.0                                                                                       
2023-11-09T17:07:10.9308382Z artifacttype              Sandbox                                                                                    
2023-11-09T17:07:10.9311529Z artifactcountry           gb                                                                                         
2023-11-09T17:07:10.9314116Z versionselect             Latest                                                                                     
2023-11-09T17:07:10.9319672Z artifacthint                                                                                                         
2023-11-09T17:07:10.9323893Z multitenant               False                                                                                      
2023-11-09T17:07:10.9378255Z memory                    8G                                                                                         
2023-11-09T17:07:10.9382669Z imageprefix               myImage                                                                                    
2023-11-09T17:07:10.9387271Z dockerregistry                                                                                                       
2023-11-09T17:07:10.9391844Z dockerusername                                                                                                       
2023-11-09T17:07:10.9397254Z dockerpassword                                                                                                       
2023-11-09T17:07:10.9402089Z storageaccount                                                                                                       
2023-11-09T17:07:10.9406518Z sastoken                                                                                                             
2023-11-09T17:07:10.9410752Z forcecreateimage          False                                                                                      
2023-11-09T17:07:10.9414873Z myscripts                                                                                                            
2023-11-09T17:07:10.9419438Z imagenametemplate         %IMAGE_PREFIX%:%ARTIFACT_TYPE%-%ARTIFACT_VERSION%-%ARTIFACT_COUNTRY%-%OS_VERSION%-%OS_LTSC%
2023-11-09T17:07:10.9424136Z licensefile                                                                                                          
2023-11-09T17:07:10.9427999Z includetesttoolkit        False                                                                                      
2023-11-09T17:07:10.9432853Z includetestlibrariesonly  False                                                                                      
2023-11-09T17:07:10.9439932Z includetestframeworkonly  False                                                                                      
2023-11-09T17:07:10.9440951Z includeperformancetoolkit False                                                                                      
2023-11-09T17:07:10.9441193Z 
2023-11-09T17:07:10.9501736Z 
2023-11-09T17:07:10.9516533Z 
2023-11-09T17:07:10.9971633Z *** For documentation, please visit   : https://www.alops.be/documentation
2023-11-09T17:07:10.9972305Z 
2023-11-09T17:07:11.2867815Z *** ALOps License:
2023-11-09T17:07:11.2977545Z   * Licensed To: Technology Management (Midlands) Limited (Enterprise License)
2023-11-09T17:07:11.2982742Z 
2023-11-09T17:07:11.3311138Z *** Importing required PS-Functions
2023-11-09T17:07:11.3963967Z *** Install/Update BCContainerHelper [https://github.com/microsoft/navcontainerhelper]
2023-11-09T17:07:11.4082721Z *** Check BcContainerHelper
2023-11-09T17:07:11.7202435Z *** Load BcContainerHelper
2023-11-09T17:07:11.9037776Z BcContainerHelper version 5.0.7
2023-11-09T17:07:12.5202121Z BC.HelperFunctions emits usage statistics telemetry to Microsoft
2023-11-09T17:07:17.0683509Z 
2023-11-09T17:07:17.0684336Z ModuleType Version    Name                                ExportedCommands                                             
2023-11-09T17:07:17.0684635Z ---------- -------    ----                                ----------------                                             
2023-11-09T17:07:17.0685030Z Script     5.0.7      BcContainerHelper                   {Add-FontsToBcContainer, Add-GitToAlProjectFolder, AddTele...
2023-11-09T17:07:17.0685225Z 
2023-11-09T17:07:17.0685291Z 
2023-11-09T17:07:17.0685364Z 
2023-11-09T17:07:17.0692409Z 
2023-11-09T17:07:17.0798383Z *** Get Artifact Url for Version [21.0] / Country [gb] / Type [Sandbox]: Latest
2023-11-09T17:07:17.1061214Z ##[command]"Get-BCArtifactUrl" 
2023-11-09T17:07:17.1061602Z Name                           Value                                                                                   
2023-11-09T17:07:17.1061960Z ----                           -----                                                                                   
2023-11-09T17:07:17.1062209Z select                         Latest                                                                                  
2023-11-09T17:07:17.1062432Z version                        21.0                                                                                    
2023-11-09T17:07:17.1062673Z type                           Sandbox                                                                                 
2023-11-09T17:07:17.1062888Z country                        gb                                                                                      
2023-11-09T17:07:17.1062977Z 
2023-11-09T17:07:17.1063044Z 
2023-11-09T17:07:17.1063160Z 
2023-11-09T17:07:18.8824229Z *** Artifact Url: [https://bcartifacts.azureedge.net/sandbox/21.0.46256.58264/gb]
2023-11-09T17:07:18.8849167Z *** Build new Image based on [https://bcartifacts.azureedge.net/sandbox/21.0.46256.58264/gb]
2023-11-09T17:07:18.8956421Z *** Artifact Type   : [sandbox]
2023-11-09T17:07:18.8993937Z *** Artifact Version: [21.0.46256.58264]
2023-11-09T17:07:18.9014514Z *** Artifact Country: [gb]
2023-11-09T17:07:19.1801688Z *** OS: [2019]
2023-11-09T17:07:21.0055398Z *** OS version: [10.0.17763.2928]
2023-11-09T17:07:21.0077062Z *** Image Template: [%IMAGE_PREFIX%:%ARTIFACT_TYPE%-%ARTIFACT_VERSION%-%ARTIFACT_COUNTRY%-%OS_VERSION%-%OS_LTSC%]
2023-11-09T17:07:21.0140269Z *** ImageName: [myimage:sandbox-21.0.46256.58264-gb-10.0.17763.2928-ltsc2019]
2023-11-09T17:07:21.0198674Z *** Set Pipeline variable $(ALOPS_BC_IMAGE) = 'myimage:sandbox-21.0.46256.58264-gb-10.0.17763.2928-ltsc2019'
2023-11-09T17:07:21.4194274Z *** Image already locally cached. Skipping Pull/Create image.
2023-11-09T17:07:21.4223312Z *** Docker Create Succeeded.
2023-11-09T17:07:21.4455592Z *** Cleanup VSTS Environment: True
2023-11-09T17:07:23.7826273Z ##[section]Finishing: ALOPS - Create Docker Image
2023-11-09T17:07:23.7861251Z ##[section]Starting: ALOpsDockerStart
2023-11-09T17:07:23.8134107Z ==============================================================================
2023-11-09T17:07:23.8134484Z Task         : ALOps Docker Start
2023-11-09T17:07:23.8134592Z Description  : Start a Business Central container
2023-11-09T17:07:23.8134725Z Version      : 1.459.5009
2023-11-09T17:07:23.8134815Z Author       : Hodor
2023-11-09T17:07:23.8134929Z Help         : Start Business Central docker container.
2023-11-09T17:07:23.8135055Z ==============================================================================
2023-11-09T17:07:25.3602093Z *** Using ALOpsDockerCreate image, disabling [docker_pull]
2023-11-09T17:07:25.3634599Z *** Importing required PS-Functions
2023-11-09T17:07:25.4506580Z *** Validate configuration
2023-11-09T17:07:25.6618729Z *** Task Inputs:
2023-11-09T17:07:25.6698448Z 
2023-11-09T17:07:25.6955250Z name                        value                                                       
2023-11-09T17:07:25.6956743Z ----                        -----                                                       
2023-11-09T17:07:25.6957048Z fixed_tag                                                                               
2023-11-09T17:07:25.6957961Z ignore_no_container_warning False                                                       
2023-11-09T17:07:25.6958746Z docker_image                myimage:sandbox-21.0.46256.58264-gb-10.0.17763.2928-ltsc2019
2023-11-09T17:07:25.6959232Z accept_image_eula           True                                                        
2023-11-09T17:07:25.6959831Z accept_image_outdated       True                                                        
2023-11-09T17:07:25.6960375Z enable_symbol_loading       False                                                       
2023-11-09T17:07:25.6960702Z enable_api_services         False                                                       
2023-11-09T17:07:25.6961108Z multitenant                 False                                                       
2023-11-09T17:07:25.6962526Z docker_pull                 True                                                        
2023-11-09T17:07:25.6963619Z dockerauthentication        None                                                        
2023-11-09T17:07:25.6965039Z docker_login                                                                            
2023-11-09T17:07:25.6965873Z docker_username                                                                         
2023-11-09T17:07:25.6966038Z docker_password                                                                         
2023-11-09T17:07:25.6969532Z docker_registry                                                                         
2023-11-09T17:07:25.6973978Z memory_gb                   8                                                           
2023-11-09T17:07:25.6980057Z container_restart           no                                                          
2023-11-09T17:07:25.6986041Z licensefile                                                                             
2023-11-09T17:07:25.6991615Z docker_parameters           --isolation=hyperv                                          
2023-11-09T17:07:25.6996432Z sql_server                                                                              
2023-11-09T17:07:25.7002930Z sql_server_instance                                                                     
2023-11-09T17:07:25.7014966Z sql_database                                                                            
2023-11-09T17:07:25.7022595Z sql_database_user                                                                       
2023-11-09T17:07:25.7024800Z sql_database_user_password                                                              
2023-11-09T17:07:25.7027922Z sql_backup_file                                                                         
2023-11-09T17:07:25.7034521Z encryption_key                                                                          
2023-11-09T17:07:25.7035123Z taskscheduler               Keep                                                        
2023-11-09T17:07:25.7035693Z 
2023-11-09T17:07:25.7077281Z 
2023-11-09T17:07:25.7092864Z 
2023-11-09T17:07:25.7597570Z *** For documentation, please visit   : https://www.alops.be/documentation
2023-11-09T17:07:25.7604524Z 
2023-11-09T17:07:26.0408418Z *** ALOps License:
2023-11-09T17:07:26.0444111Z   * Licensed To: Technology Management (Midlands) Limited (Enterprise License)
2023-11-09T17:07:26.0451490Z 
2023-11-09T17:07:26.5464531Z *** Splitting Additional Docker Parameters
2023-11-09T17:07:26.5481459Z *** Additional Docker parameters:
2023-11-09T17:07:26.5552998Z --isolation=hyperv
2023-11-09T17:07:26.5718717Z *** Add docker parameter: --isolation=hyperv
2023-11-09T17:07:26.5720452Z ##[command]"docker" create --memory 8G --env accept_eula=Y --env accept_outdated=Y --restart no --label TFSBuild=Tecman.AFU001.ReportPack_70077 --isolation=hyperv myimage:sandbox-21.0.46256.58264-gb-10.0.17763.2928-ltsc2019
2023-11-09T17:07:26.9965790Z *** Checking for Assemblies in App
2023-11-09T17:07:27.0231811Z ##[command]"docker" start eea673369a1d5091bc4d12c868a5a981f88f861053860d37c7ef2b95c5364c32
2023-11-09T17:07:42.4346003Z Error response from daemon: hcsshim::CreateComputeSystem eea673369a1d5091bc4d12c868a5a981f88f861053860d37c7ef2b95c5364c32: This operation returned because the timeout period expired.
2023-11-09T17:07:42.4361484Z (extra info: {"SystemType":"Container","Name":"eea673369a1d5091bc4d12c868a5a981f88f861053860d37c7ef2b95c5364c32","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"E:\\ProgramData\\docker\\windowsfilter\\eea673369a1d5091bc4d12c868a5a981f88f861053860d37c7ef2b95c5364c32","Layers":[{"ID":"a78e9cbd-45a9-547a-9d02-a905b6b2844c","Path":"E:\\ProgramData\\docker\\windowsfilter\\34b13872051bf36b39fc8f3e0c31da636144fe40973039b974f23e53a69471b2"},{"ID":"2ce1cfec-1608-5598-8ad0-55dfe37a5e66","Path":"E:\\ProgramData\\docker\\windowsfilter\\327c9dc57c48dea4408af833b4ca0a66c32443d5bf0b17f08cbcc8a947b7b3f4"},{"ID":"308992ae-0c3f-51b9-8228-dcdf888da08e","Path":"E:\\ProgramData\\docker\\windowsfilter\\66bea357669f27a95f7064153c8c73bc704fa0b6c5bd4d7d7e7ab390ce368fc1"},{"ID":"488b22f9-bc52-51e8-98d5-376fb30b60bd","Path":"E:\\ProgramData\\docker\\windowsfilter\\f762e60d4dd7a5baf43c61c6738936c9c011808333540e46b9280823da6b9bca"},{"ID":"535b9dd5-fe55-5fd9-9068-86fa2e7ae3d0","Path":"E:\\ProgramData\\docker\\windowsfilter\\a5c6fbf29164e85c898e45da57c8d54ab8ccaeab238e42cbb1660f70dc38953b"},{"ID":"0d169596-34b6-538d-b8f8-146066d3d5e7","Path":"E:\\ProgramData\\docker\\windowsfilter\\89c97a4648f9966934b6be159d6e8e73fe78256babd0e0c7333963b16b40a6d7"},{"ID":"7c2c82fc-e29a-5c43-9d03-9793f063ac12","Path":"E:\\ProgramData\\docker\\windowsfilter\\0e128882c5e2acd28ed77ccb0ea1099035f667474c60fed3a12fb1f24d2d689d"},{"ID":"80b0d8d6-d667-5f99-b362-d9c120621bac","Path":"E:\\ProgramData\\docker\\windowsfilter\\4bef66a52e964456cf2a7206cf3fb0950a3c6da8f95d2abdaceb315e4abcc06e"},{"ID":"f01ec8c2-3b1d-5718-a508-c2192c9cf200","Path":"E:\\ProgramData\\docker\\windowsfilter\\f089b523ce9840398e10ec8d40308cbf8291994c99db7c083b0e4d8191605d25"},{"ID":"4bd6f1aa-8d07-56e0-bdd7-5e408d2bacc1","Path":"E:\\ProgramData\\docker\\windowsfilter\\3a0c6bb7892ac503ae3de622b4be74e7f23b10b1faa9ca16c2e7f4b4f79f0d7b"},{"ID":"50368b3a-c3e0-5a86-a904-adbd55945fd6","Path":"E:\\ProgramData\\docker\\windowsfilter\\17b792374ae39cae8092354bfa1921e271e5b6729c3d27880ae29cabd03c2179"},{"ID":"70be9b9f-4929-5443-9046-c1ba37734ef1","Path":"E:\\ProgramData\\docker\\windowsfilter\\7e653e17f78c380ee56eeba14898f7923e41721e233d230b664f0c5097a877fd"},{"ID":"7c7bb4d9-0098-5c42-a7f9-11175fc02394","Path":"E:\\ProgramData\\docker\\windowsfilter\\9f309322c2ade05d47f726b585da5bb62f9bad8305bd30347b2f71d46e71a64e"},{"ID":"3d49b9a8-6545-5036-bd91-1fb3c0c07ad7","Path":"E:\\ProgramData\\docker\\windowsfilter\\b032d60791841e7d0cbc69f6dc4ecfa2856233b964e012cd181848256ac805f6"},{"ID":"5e4a7423-deb9-5d6d-a3f7-66117909df2f","Path":"E:\\ProgramData\\docker\\windowsfilter\\28e53e37b1ba31b8a393c8888e202b6ad45d4edb18710bf814e5a3645cd1bc4c"},{"ID":"5b68ef23-03b4-5f9f-9fd9-fb41c4b6dfa9","Path":"E:\\ProgramData\\docker\\windowsfilter\\deac84cd75566ab6c9401dd17a642a2779ab0d470bc295b42265c5156c8b451a"},{"ID":"acde99a8-18ba-58b9-9130-d88c906be7b0","Path":"E:\\ProgramData\\docker\\windowsfilter\\230fa590270ccc6a58a822f22079c9b552132d407b17da856a46d47ee24e2d03"},{"ID":"6a2669c3-f9b7-5211-935d-6f6d889dbe42","Path":"E:\\ProgramData\\docker\\windowsfilter\\4d5ad2764aaf21ba5fcbf49d11e2494b55e9b5434aa7a63c522b99238070b3b9"},{"ID":"d43e009c-e93f-5608-9777-93536bcd2281","Path":"E:\\ProgramData\\docker\\windowsfilter\\4ae853ebb2b2ba958c4ca87f88c9582fceed04290ea750e1c6a6d2dcca83571f"},{"ID":"5f88ce23-235b-5ebf-aa39-9c24a41c296d","Path":"E:\\ProgramData\\docker\\windowsfilter\\320168f9cb88f42bb84f46a898a26c811557efb6bad8b2fda451894ac18444c0"},{"ID":"6421d1a3-501a-5d04-a95e-58f33d0134d3","Path":"E:\\ProgramData\\docker\\windowsfilter\\b4f849debb40e12b9ed2fd0ce27757d206aa8a2c5b0050325a81aa39d1c8f090"},{"ID":"a8f5ad17-cd1b-5fd0-b5c0-136755a479be","Path":"E:\\ProgramData\\docker\\windowsfilter\\c82e7015fe1183a49ae527a5f0c13910dec262a497a3602e2959135d583b8f83"},{"ID":"8ba6445d-f114-57e8-a76f-e9906107961c","Path":"E:\\ProgramData\\docker\\windowsfilter\\d2c66c497c52e673682d9a854a8ff4685fe09257e4a41673834e460973f5d0af"},{"ID":"6bcbc59c-ef3d-5c26-9e23-907c27110986","Path":"E:\\ProgramData\\docker\\windowsfilter\\a56c3dccdf4b67920b81e5651d0b60f973ae6acf4783279f471ffbd771a61563"},{"ID":"5667ef3c-e88d-5904-bf84-cf7c9165647d","Path":"E:\\ProgramData\\docker\\windowsfilter\\618bc9b204b19fe2b4c00890c539efe2dbb11fe53282f1aa46374f00ef41bb3a"},{"ID":"2738cf9e-9253-5344-b61e-46a892278091","Path":"E:\\ProgramData\\docker\\windowsfilter\\c7a7af300b12d860703b1844e9c67cca392814325062a503f968de9ba7e3759e"},{"ID":"82fdf487-6308-5a84-a6d1-3998952dc36a","Path":"E:\\ProgramData\\docker\\windowsfilter\\37f4ec20a779ca3db3f338be61ed24eb62173fd5645df3171c65eed29f53a69f"},{"ID":"5948314d-d5d9-591f-8afb-19730759a40b","Path":"E:\\ProgramData\\docker\\windowsfilter\\7bf6df14a6d46c1cae117715c6e9cd65e139f69bcb9d665bd813d4933638fe8b"},{"ID":"e661d7e7-bc7a-51bb-a1bf-9a6b97707c95","Path":"E:\\ProgramData\\docker\\windowsfilter\\c3da7f1319728ea6b116e3a1f977d7e55ffd56011b4cc45df150ce29fe9a39d4"},{"ID":"daddf32c-b991-57f7-bb16-bc6061b70ab3","Path":"E:\\ProgramData\\docker\\windowsfilter\\fbedc89da6174f2e89d2c51bf53ff0aded5eca0c722981f93c4ef898578fdeed"},{"ID":"5637d1e7-5814-5512-baa6-292cf10469a6","Path":"E:\\ProgramData\\docker\\windowsfilter\\2dca683e5ea2cd7fd27a492c0f732c5a5ece74eeb6afa2613e780d2ab36988fa"}],"MemoryMaximumInMB":8192,"HostName":"eea673369a1d","HvPartition":true,"EndpointList":["0A9D2E5E-E9D3-412C-B052-AFEA4DB1EE26"],"HvRuntime":{"ImagePath":"E:\\ProgramData\\docker\\windowsfilter\\fbedc89da6174f2e89d2c51bf53ff0aded5eca0c722981f93c4ef898578fdeed\\UtilityVM"},"AllowUnqualifiedDNSQuery":true})
2023-11-09T17:07:42.4366072Z Error: failed to start containers: eea673369a1d5091bc4d12c868a5a981f88f861053860d37c7ef2b95c5364c32
2023-11-09T17:07:42.4503524Z *** Container Started: eea673369a1d5091bc4d12c868a5a981f88f861053860d37c7ef2b95c5364c32
2023-11-09T17:07:42.8534850Z *** Container Labels:
2023-11-09T17:07:42.8610179Z 
2023-11-09T17:07:42.9471756Z *** Docker Start OK.
2023-11-09T17:07:42.9471891Z *** Cleanup VSTS Environment: True
2023-11-09T17:07:44.9966699Z ##[section]Async Command Start: Add Build Tag
2023-11-09T17:07:44.9967132Z Build '70077' has following tags now: AL.Analyzer.CodeCop, AL.Analyzer.PerTenantExtensionCop, AL.Analyzer.UICop, myimage-sandbox-21.0.46256.58264-gb-10.0.17763.2928-ltsc2019
2023-11-09T17:07:44.9967506Z ##[section]Async Command End: Add Build Tag
2023-11-09T17:07:44.9968536Z ##[section]Async Command Start: Add Build Tag
2023-11-09T17:07:44.9969032Z Build '70077' has following tags now: AL.Analyzer.CodeCop, AL.Analyzer.PerTenantExtensionCop, AL.Analyzer.UICop, myimage-sandbox-21.0.46256.58264-gb-10.0.17763.2928-ltsc2019, BC.Platform.21.0.46384.58215
2023-11-09T17:07:44.9969743Z ##[section]Async Command End: Add Build Tag
2023-11-09T17:07:44.9971040Z ##[section]Async Command Start: Add Build Tag
2023-11-09T17:07:44.9971741Z Build '70077' has following tags now: AL.Analyzer.CodeCop, AL.Analyzer.PerTenantExtensionCop, AL.Analyzer.UICop, myimage-sandbox-21.0.46256.58264-gb-10.0.17763.2928-ltsc2019, BC.Version.21.0.46256.58264, BC.Platform.21.0.46384.58215
2023-11-09T17:07:44.9972238Z ##[section]Async Command End: Add Build Tag
2023-11-09T17:07:44.9973419Z ##[section]Finishing: ALOpsDockerStart
2023-11-09T17:07:45.0001259Z ##[section]Starting: ALOpsDockerWait
2023-11-09T17:07:45.0226499Z ==============================================================================
2023-11-09T17:07:45.0226603Z Task         : ALOps Docker Wait
2023-11-09T17:07:45.0226678Z Description  : Wait until the Business Central container is started
2023-11-09T17:07:45.0226752Z Version      : 1.459.5009
2023-11-09T17:07:45.0227018Z Author       : Hodor
2023-11-09T17:07:45.0227061Z Help         : Wait until the Business Central container is started.
2023-11-09T17:07:45.0227128Z ==============================================================================
2023-11-09T17:07:46.5350550Z *** Validate configuration
2023-11-09T17:07:46.6278931Z *** Task Inputs:
2023-11-09T17:07:46.6340045Z 
2023-11-09T17:07:46.6465237Z name                 value                 
2023-11-09T17:07:46.6469169Z ----                 -----                 
2023-11-09T17:07:46.6472174Z fixed_tag                                  
2023-11-09T17:07:46.6478561Z search_string        Ready for connections!
2023-11-09T17:07:46.6481695Z warning_string                             
2023-11-09T17:07:46.6486959Z error_string                               
2023-11-09T17:07:46.6491953Z setup_working_folder True                  
2023-11-09T17:07:46.6496892Z usecompression       True                  
2023-11-09T17:07:46.6549189Z printlogs            True                  
2023-11-09T17:07:46.6549371Z 
2023-11-09T17:07:46.6590968Z 
2023-11-09T17:07:46.6599621Z 
2023-11-09T17:07:46.6926886Z *** For documentation, please visit   : https://www.alops.be/documentation
2023-11-09T17:07:46.6933673Z 
2023-11-09T17:07:47.0251173Z *** ALOps License:
2023-11-09T17:07:47.0266308Z   * Licensed To: Technology Management (Midlands) Limited (Enterprise License)
2023-11-09T17:07:47.0275461Z 
2023-11-09T17:07:47.0547282Z *** Importing required PS-Functions
2023-11-09T17:07:47.6882370Z *** Waiting for Docker Container Log Entry: Ready for connections!
2023-11-09T17:07:49.1435805Z 
2023-11-09T18:05:21.6613149Z ##[error]The operation was canceled.
2023-11-09T18:05:21.6617409Z ##[section]Finishing: ALOpsDockerWait
2023-11-09T18:05:21.6639603Z Skipping step due to condition evaluation.
Evaluating: SucceededNode()
Result: False

2023-11-09T18:05:21.6659060Z Skipping step due to condition evaluation.
Evaluating: SucceededNode()
Result: False

2023-11-09T18:05:21.6683362Z Skipping step due to condition evaluation.
Evaluating: SucceededNode()
Result: False

2023-11-09T18:05:21.6707693Z Skipping step due to condition evaluation.
Evaluating: SucceededNode()
Result: False

2023-11-09T18:05:21.6728535Z Skipping step due to condition evaluation.
Evaluating: SucceededNode()
Result: False

2023-11-09T18:05:21.6751579Z Skipping step due to condition evaluation.
Evaluating: SucceededNode()
Result: False

2023-11-09T18:05:21.6773597Z ##[section]Starting: ALOps Remove Docker Container
2023-11-09T18:05:21.6942124Z ==============================================================================
2023-11-09T18:05:21.6942236Z Task         : ALOps Docker Remove

```

**Expected behavior**
When the Docker Start task reports an error it should fail the pipeline.

**Screenshots**
![image](https://github.com/HodorNV/ALOps/assets/17627914/1e861cac-c715-4df2-ab25-b2aec4d91782)
![image](https://github.com/HodorNV/ALOps/assets/17627914/60b908c9-fd9f-448d-be28-7c59723d40e2)

**Additional context**
Checking the agent I can see the docker container is in a created state. not running.
I tried adding a new task to check the container is reporting a 'running' status using the global variable ALOPS_DOCKER_CONTAINER_ID. This is not populated after the DockerStart task, could it be? The ContainerId is known at this point.

**Comment by waldo1001** [comment]
Hm - we'll look into this - it should indeed have failed right away.

**Comment by AdminHodor** [comment]
Dear @deano808 ,

Please check out our latest release v1.461. We improved the docker.exe command handling which should solve this issue.

Kind regards,

**Comment by deano808** [comment]
Hello,
Unfortunately, the issue remains. The Docker Start task has failed but not stopped the pipeline. (see below)
fyi, when I see a pipeline in this condition, if I stop the created container and then start it the pipeline continues.


Starting: ALOpsDockerStart
==============================================================================
Task         : ALOps Docker Start
Description  : Start a Business Central container
Version      : 1.461.5079
Author       : Hodor
Help         : Start Business Central docker container.
==============================================================================
*** Using ALOpsDockerCreate image, disabling [docker_pull]
*** Importing required PS-Functions
*** Validate configuration
*** Task Inputs:

name                        value                                                       
----                        -----                                                       
fixed_tag                                                                               
ignore_no_container_warning False                                                       
docker_image                myimage:sandbox-22.0.54157.62224-gb-10.0.17763.3046-ltsc2019
accept_image_eula           True                                                        
accept_image_outdated       True                                                        
enable_symbol_loading       False                                                       
enable_api_services         False                                                       
multitenant                 False                                                       
docker_pull                 True                                                        
dockerauthentication        None                                                        
docker_login                                                                            
docker_username                                                                         
docker_password                                                                         
docker_registry                                                                         
memory_gb                   8                                                           
container_restart           no                                                          
licensefile                                                                             
docker_parameters           --isolation=hyperv                                          
sql_server                                                                              
sql_server_instance                                                                     
sql_database                                                                            
sql_database_user                                                                       
sql_database_user_password                                                              
sql_backup_file                                                                         
encryption_key                                                                          
taskscheduler               Keep                                                        



*** For documentation, please visit   : https://www.alops.be/documentation

*** ALOps License:
  * Licensed To: Technology Management (Midlands) Limited (Enterprise License)

*** Splitting Additional Docker Parameters
*** Additional Docker parameters:
--isolation=hyperv
*** Add docker parameter: --isolation=hyperv
"docker" create --memory 8G --env accept_eula=Y --env accept_outdated=Y --restart no --label TFSBuild=Tecman.STO004.BulkOrders_71098 --isolation=hyperv myimage:sandbox-22.0.54157.62224-gb-10.0.17763.3046-ltsc2019
*** Checking for Assemblies in App
"docker" start f36c467d7b89029ea4cd0f4d7e01c17da7612d71a7057a014c1c2669b5092181
Error response from daemon: hcsshim::CreateComputeSystem f36c467d7b89029ea4cd0f4d7e01c17da7612d71a7057a014c1c2669b5092181: This operation returned because the timeout period expired.
(extra info: {"SystemType":"Container","Name":"f36c467d7b89029ea4cd0f4d7e01c17da7612d71a7057a014c1c2669b5092181","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"F:\\ProgramData\\docker\\windowsfilter\\f36c467d7b89029ea4cd0f4d7e01c17da7612d71a7057a014c1c2669b5092181","Layers":[{"ID":"bbd84837-2da6-5545-b782-93cab41ee821","Path":"F:\\ProgramData\\docker\\windowsfilter\\e481b6d4dff995f75ebcb88163eb5ee5dd92364481076d5374a51fd0c6cbed28"},{"ID":"ddc7da26-dd55-5244-99d9-8a3b385583b7","Path":"F:\\ProgramData\\docker\\windowsfilter\\3fa23006559fb26dfd06ffecade4db8b44fcc6e181693313abf44b969c14299b"},{"ID":"f54b9849-5fa9-51aa-a3c3-6991a747de8a","Path":"F:\\ProgramData\\docker\\windowsfilter\\a8c8cf8744318a2b57f860a203153079c42c474e9ae95f0a180e15999e98596a"},{"ID":"fe11ffa4-cd7d-50bd-a911-e1accf92aff8","Path":"F:\\ProgramData\\docker\\windowsfilter\\191a2f97138bd4f51f1802f79e2115c56e6fd535bbae831753ce8e7d39bbca53"},{"ID":"40f5acd7-e306-5e1c-9ebd-f5202c2425ed","Path":"F:\\ProgramData\\docker\\windowsfilter\\10eab03bc33087675ac42b8088babf14b6aa27e440176173e7af8928880e064a"},{"ID":"5270f549-70bd-5a58-97c7-a9b84fbcf310","Path":"F:\\ProgramData\\docker\\windowsfilter\\a0ff84b68716099034e60cfceb36487d8b96e72f5719a6b35fe962baedd3a4a7"},{"ID":"5afae811-65e4-5318-bf8d-afce57312ac3","Path":"F:\\ProgramData\\docker\\windowsfilter\\3e59429b401f6f1ad218d6f574a4f04b4a3a1beb8941c2cb763c0352660cf97b"},{"ID":"0eca9393-a20a-5847-a91c-8a2ad3b92e01","Path":"F:\\ProgramData\\docker\\windowsfilter\\e9dfb166a50adb48b77214c93080d6eda8d1299e076d5db51fd3c1311cccf124"},{"ID":"b0b9c2e9-c132-552a-b58b-aa7d748704f0","Path":"F:\\ProgramData\\docker\\windowsfilter\\6b56e41dcb6d7eb812698adad047ed8c4405b8fba68fda0711038ee62a508562"},{"ID":"83697db6-5b2b-50af-b714-87b3f22bf8a5","Path":"F:\\ProgramData\\docker\\windowsfilter\\1936459bde76a3a1d4e37ea03acb1bf2df3a9928ba6e5dd656df1b827f546064"},{"ID":"ab06f61c-7598-5542-b2fa-4887de3678c9","Path":"F:\\ProgramData\\docker\\windowsfilter\\64e0e6c96ff762a63f25d305c4345694092b82a43bec8fa4f0115b1ae538628a"},{"ID":"67c17c32-9d56-5a9a-8fef-31a047b4e6cf","Path":"F:\\ProgramData\\docker\\windowsfilter\\0189ced5af8b6705e0a26b64a8991afe19633f978ac06e02f7cf1f4ef8c95542"},{"ID":"2ff03125-c5ca-57f3-92ff-f75ecbaaad09","Path":"F:\\ProgramData\\docker\\windowsfilter\\7d6d6d8aceee520d034962eafb9cd19452a826d4240aebccbe19cfba5caa6ab8"},{"ID":"7468e19e-f6c3-5fa0-997d-5cba6de0992b","Path":"F:\\ProgramData\\docker\\windowsfilter\\57b3b651c39a38abb1318e62ef470bf115f2ecb1be456b2a23b901faea762a75"},{"ID":"ae3c3638-c53a-5bc4-855d-761ec8343018","Path":"F:\\ProgramData\\docker\\windowsfilter\\56b407d099a5e9e40d887305d2f16a3417c0cd5808fb3bdf4c679574c90562bb"},{"ID":"f4498c75-30b8-594c-b425-1405ff655660","Path":"F:\\ProgramData\\docker\\windowsfilter\\750c29bcc7b5c23ee4e21f9f21279a5525dd1eca37e4158991e7f94b96b89d25"},{"ID":"f448ef62-118d-5b96-a6f9-6c358d30bcbc","Path":"F:\\ProgramData\\docker\\windowsfilter\\9b2928994d6544082d3403de2c1937d306a92f81986373e5ef7baf9f7fafcd2a"},{"ID":"f849e734-91a5-5341-9543-2b0058c3a716","Path":"F:\\ProgramData\\docker\\windowsfilter\\c8fdefda0c744083083c649995d4619deb16573d5718b650c02eb3a50c5708cc"},{"ID":"aae7200d-1707-554b-8894-ab5f7e0903d1","Path":"F:\\ProgramData\\docker\\windowsfilter\\e60657561d9f11bf0115dd576a533ac956f6426c63ceb25d0da8e8dba3132c37"},{"ID":"e91e9151-6f22-5d3f-b528-0cef473ad046","Path":"F:\\ProgramData\\docker\\windowsfilter\\e0d6d3d1cf9444eb60d5f5986dd28b5574529173b60cfb3766d744bfafae3298"},{"ID":"4884642f-bb55-5094-9439-c1b0e7eaede5","Path":"F:\\ProgramData\\docker\\windowsfilter\\279a70b452302fbf04076658018d5e1b5247a225c779dc6b7f8eb3ce26c2969e"},{"ID":"5dade298-2712-57b4-aa04-1771bc8d0ebc","Path":"F:\\ProgramData\\docker\\windowsfilter\\5ed4e6d4a878e27ba8bfe3ae4330b87fe94c4aa0a7015c97c098917894445f3b"},{"ID":"178365dd-03eb-5278-9bae-6baa142872d0","Path":"F:\\ProgramData\\docker\\windowsfilter\\31b034d951c79361cdf430908533cf81cd235a458d1c3ead97556f2150c21295"},{"ID":"28bd5eea-5e9e-5a97-a7ad-4b1f9187b291","Path":"F:\\ProgramData\\docker\\windowsfilter\\9c0a24ee18ea192ef5172c49d618b80b56267b18e2a8f20f6901dc9996f0eef5"},{"ID":"d4ce109f-58fe-5680-bfe0-4d10d5861df6","Path":"F:\\ProgramData\\docker\\windowsfilter\\d2a98cc44d41480d4fbcf7c82bb0edb2838762c9f6e49e31665320687f60990e"},{"ID":"abf975b0-3f5a-5d50-8ab4-9db0b8b803d8","Path":"F:\\ProgramData\\docker\\windowsfilter\\30953fe36f8fd6a6771f5df70f95d7675dee316312ac7eed87d540ca2246f47d"},{"ID":"355b8604-148c-5dfe-a83a-c0af8d18d693","Path":"F:\\ProgramData\\docker\\windowsfilter\\e248200027f6bf569e438058c1a7d2115092feb15cdbe5706b70a0cecc61b508"},{"ID":"6d922021-4ba5-5b39-9833-32b24209a8ef","Path":"F:\\ProgramData\\docker\\windowsfilter\\cef01bf0c9e4b818562a172c06add253603908c34e411d0495171a589ab65511"},{"ID":"17775fae-c97d-525a-a694-eec51b7648f3","Path":"F:\\ProgramData\\docker\\windowsfilter\\f986ebd6038b8e3ceb425f0c4f74b3264a946cc85b7e88adf5e932fe916c4acc"}],"MemoryMaximumInMB":8192,"HostName":"f36c467d7b89","HvPartition":true,"EndpointList":["5B590D84-B80E-439F-ACFF-D3D78F95460C"],"HvRuntime":{"ImagePath":"F:\\ProgramData\\docker\\windowsfilter\\cef01bf0c9e4b818562a172c06add253603908c34e411d0495171a589ab65511\\UtilityVM"},"AllowUnqualifiedDNSQuery":true})
Error: failed to start containers: f36c467d7b89029ea4cd0f4d7e01c17da7612d71a7057a014c1c2669b5092181
*** Container Started: f36c467d7b89029ea4cd0f4d7e01c17da7612d71a7057a014c1c2669b5092181
*** Container Labels:

*** Docker Start OK.
*** Cleanup VSTS Environment: True
Async Command Start: Add Build Tag
Build '71098' has following tags now: AL.Analyzer.PerTenantExtensionCop, AL.Analyzer.UICop, AL.Analyzer.CodeCop, myimage-sandbox-22.0.54157.62224-gb-10.0.17763.3046-ltsc2019
Async Command End: Add Build Tag
Async Command Start: Add Build Tag
Build '71098' has following tags now: AL.Analyzer.PerTenantExtensionCop, AL.Analyzer.UICop, AL.Analyzer.CodeCop, myimage-sandbox-22.0.54157.62224-gb-10.0.17763.3046-ltsc2019, BC.Platform.22.0.62215.0, BC.Version.22.0.54157.62224
Async Command End: Add Build Tag
Async Command Start: Add Build Tag
Build '71098' has following tags now: AL.Analyzer.PerTenantExtensionCop, AL.Analyzer.UICop, AL.Analyzer.CodeCop, myimage-sandbox-22.0.54157.62224-gb-10.0.17763.3046-ltsc2019, BC.Version.22.0.54157.62224
Async Command End: Add Build Tag
Finishing: ALOpsDockerStart

**Comment by waldo1001** [comment]
Hi,

can you please mail us a full log to admin@hodor.be so we can investigate further?

thanks,

/waldo
