### ISSUE TITLE
Error: There is not enough space on the disk.

### ISSUE THREAD

**Issue by ThomasWat** [HodorNV/ALOps#810]
**Describe the bug**
On the` ALOpsAppCompiler@1` step I receive the error `There is not enough space on the disk.`

I tried a few times more but it keeps giving me the same error.

**the used yaml**
```yaml
#name: $(Build.BuildId)
name: ERP_BC_Build

trigger:
  branches:
    include:
      - 05.Test/Test
      - 04.Development/Development
      - 01.Main/Main

variables:
- group: 'BuildVariables'  # link to a variable group that has secret variables, like URL to license file, or sasToken for insider builds
- name: AppVersion
  value: ?.?.*.0
- name: BCVersion
  value: 19.6
- name: bc.license
  value: "$(System.DefaultWorkingDirectory)/.license/5118527.bclicense"

pool: ALOps

steps:
- checkout: self
  clean: true 

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/.apps'
    ArtifactName: 'DependentApps'
    publishLocation: 'Container'

- task: ALOpsDockerCreate@1
  displayName: 'ALOps - Create Docker Image if necessary' # It will reuse the image if already exists, or build one if it doesn't.
  inputs:
    artifacttype: OnPrem
    artifactversion: $(BCVersion)
    artifactcountry: be
    licensefile: '$(bc.license)'

- task: ALOpsDockerStart@1
  displayName: 'ALOps - Start Docker Container' # No need to provide any details - it will get the details from previous step
  inputs:
    docker_pull: false
    enable_api_services: true
    docker_parameters: | 
      --env customNavSettings=EnableTaskScheduler=false

- task: ALOpsDockerWait@1
  displayName: 'ALOps - Wait for Docker Container to start'
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  displayName: 'ALOps - Update License'
  inputs:
    usedocker: true
    license_path: '$(System.DefaultWorkingDirectory)/.license/5118527.bclicense'
    print_license_info: true

- task: ALOpsAppPublish@1
  displayName: 'ALOps - Install Dependent Apps'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    batch_publish_folder: '.apps'

- task: ALOpsAppCompiler@1
  displayName: 'ALOps - Compile Extension: App'
  inputs:
    usedocker: true
    nav_app_version: $(AppVersion)                          # ? = Take digit from the app.json, * = buildnumber
    targetproject: 'app/app.json'                           # The App
    failed_on_warnings: false
    app_file_suffix: '_APP'                                 # A trick to uniquely identify the APP (from the TEST-app)

- task: ALOpsAppPublish@1
  displayName: 'ALOps - Publish Extension'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    skip_verification: true

- task: ALOpsOpenAPI@1
  inputs:
    usedocker: true
    api_endpoint: 'https://$(ALOPS_DOCKER_HOSTNAME):7048/bc/api'
    authentication: 'basic'
    username: '$(ALOPS_DOCKER_ADMINUSER)'
    password: '$(ALOPS_DOCKER_ADMINPASSWORD)'
    export_yaml: true
    export_edmx: true
    discover: true
    publish_artifacts: true
    api_exclude_routes: |
        beta
        v1.0
    api_routes: |
        hodor/purchase/v1.0
    inspect_paths: true

- task: ALOpsInfo@1

- task: ALOpsDockerRemove@1
  displayName: 'ALOps - Remove Docker Container'
  condition: always()
  
- task: ALOpsAgentMaintenance@1
  inputs:
    removeoldtasks: true
    removeunusedcontainers: true
    pruneimagesdayscreated: '7'
    pruneimagesosbased: true
    removebcartifacts: true
```

**the output**
```
2024-11-15T10:47:49.9819948Z ##[section]Starting: ALOps - Compile Extension: App
2024-11-15T10:47:49.9958360Z ==============================================================================
2024-11-15T10:47:49.9958681Z Task         : ALOps App Compiler
2024-11-15T10:47:49.9958914Z Description  : Compile AL Extensions for Business Central
2024-11-15T10:47:49.9959153Z Version      : 1.466.6319
2024-11-15T10:47:49.9959327Z Author       : Hodor
2024-11-15T10:47:49.9959553Z Help         : Compile a Business Central extension from AL code.
2024-11-15T10:47:49.9959847Z ==============================================================================
2024-11-15T10:47:50.7458975Z *** Validate configuration
2024-11-15T10:47:50.8336838Z *** Task Inputs:
2024-11-15T10:47:50.8382566Z 
2024-11-15T10:47:50.8549990Z name                                                                                         value
2024-11-15T10:47:50.8557548Z ----                                                                                         -----
2024-11-15T10:47:50.8562831Z usedocker                                                                                     True
2024-11-15T10:47:50.8566258Z fixed_tag                                                                                         
2024-11-15T10:47:50.8570733Z targetproject                                    C:\vsts-agent-alops-warp10\_work\2\s\app\app.json
2024-11-15T10:47:50.8573962Z nav_computername                                                                                  
2024-11-15T10:47:50.8576899Z nav_serverinstance                                                                           BC140
2024-11-15T10:47:50.8579950Z nav_tenant                                                                                 default
2024-11-15T10:47:50.8583345Z nav_ports_dev                                                                                 7049
2024-11-15T10:47:50.8586590Z bc_username                                                                                       
2024-11-15T10:47:50.8589640Z bc_password                                                                                       
2024-11-15T10:47:50.8592697Z al_compiler_version                                                                     0.12.15355
2024-11-15T10:47:50.8595614Z ruleset                                                                                           
2024-11-15T10:47:50.8598842Z suppresswarnings                                                                              KEEP
2024-11-15T10:47:50.8601873Z al_analyzer                                                                                       
2024-11-15T10:47:50.8604784Z ignorepragmas                                                                                     
2024-11-15T10:47:50.8608103Z nav_app_version                                                                            ?.?.*.0
2024-11-15T10:47:50.8610747Z vsix_download_path                                                                                
2024-11-15T10:47:50.8613950Z use_ssl                                                                                      False
2024-11-15T10:47:50.8617046Z download_test_symbols                                                                        False
2024-11-15T10:47:50.8619905Z usecompression                                                                                True
2024-11-15T10:47:50.8623150Z publish_artifact                                                                              True
2024-11-15T10:47:50.8626196Z publishxlif                                                                                  False
2024-11-15T10:47:50.8629089Z failed_on_warnings                                                                           False
2024-11-15T10:47:50.8632288Z failonany                                                                                    False
2024-11-15T10:47:50.8635707Z app_file_suffix                                                                               _APP
2024-11-15T10:47:50.8638952Z updatebuildnumber                                                                             True
2024-11-15T10:47:50.8642009Z setup_working_folder                                                                         False
2024-11-15T10:47:50.8644872Z showmycode                                                                                    Keep
2024-11-15T10:47:50.8648231Z resourceexposurepolicy_allowdebugging                                                         Keep
2024-11-15T10:47:50.8651179Z resourceexposurepolicy_allowdownloadingsource                                                 Keep
2024-11-15T10:47:50.8654479Z resourceexposurepolicy_includesourceinsymbolfile                                              Keep
2024-11-15T10:47:50.8657448Z internalsvisibleto                                                                            Keep
2024-11-15T10:47:50.8660333Z preprocessorsymbols                                                                               
2024-11-15T10:47:50.8663584Z applicationinsightskey                                                                            
2024-11-15T10:47:50.8666319Z printappmanifest                                                                              True
2024-11-15T10:47:50.8669575Z output_alc_logs                                                                               True
2024-11-15T10:47:50.8672638Z additionalprobingpaths                                                                            
2024-11-15T10:47:50.8675518Z enable_external_rulesets                                                                     False
2024-11-15T10:47:50.8678760Z allowed_publisher_names                                                                           
2024-11-15T10:47:50.8681814Z allowed_publisher_names_separator                                                                ,
2024-11-15T10:47:50.8682130Z 
2024-11-15T10:47:50.8706432Z 
2024-11-15T10:47:50.8714911Z 
2024-11-15T10:47:50.8878682Z True
2024-11-15T10:47:50.9070215Z *** For documentation, please visit   : https://www.alops.be/documentation
2024-11-15T10:47:50.9075348Z 
2024-11-15T10:47:51.1747402Z *** ALOps License:
2024-11-15T10:47:51.1836057Z   * Licensed To: Duvel Moortgat (RepositoryPer5 License)
2024-11-15T10:47:51.1847323Z 
2024-11-15T10:47:51.2067207Z *** Importing required PS-Functions
2024-11-15T10:47:51.3792027Z *** Initiate Docker Session
2024-11-15T10:47:51.6462514Z *** Set Docker Container ErrorActionPreference = Stop
2024-11-15T10:47:51.6978383Z *** Container Session Powershell Version
2024-11-15T10:47:51.7769874Z 
2024-11-15T10:47:51.7770551Z 
2024-11-15T10:47:51.7771115Z Name  : PSVersion
2024-11-15T10:47:51.7771487Z Value : 5.1.17763.6530
2024-11-15T10:47:51.7771686Z 
2024-11-15T10:47:51.7772025Z Name  : PSEdition
2024-11-15T10:47:51.7772324Z Value : Desktop
2024-11-15T10:47:51.7772431Z 
2024-11-15T10:47:51.7772668Z Name  : PSCompatibleVersions
2024-11-15T10:47:51.7772925Z Value : {1.0, 2.0, 3.0, 4.0...}
2024-11-15T10:47:51.7773049Z 
2024-11-15T10:47:51.7773259Z Name  : BuildVersion
2024-11-15T10:47:51.7773494Z Value : 10.0.17763.6530
2024-11-15T10:47:51.7773604Z 
2024-11-15T10:47:51.7773804Z Name  : CLRVersion
2024-11-15T10:47:51.7774041Z Value : 4.0.30319.42000
2024-11-15T10:47:51.7774151Z 
2024-11-15T10:47:51.7774360Z Name  : WSManStackVersion
2024-11-15T10:47:51.7774582Z Value : 3.0
2024-11-15T10:47:51.7774676Z 
2024-11-15T10:47:51.7774896Z Name  : PSRemotingProtocolVersion
2024-11-15T10:47:51.7775133Z Value : 2.3
2024-11-15T10:47:51.7775231Z 
2024-11-15T10:47:51.7775440Z Name  : SerializationVersion
2024-11-15T10:47:51.7775677Z Value : 1.1.0.1
2024-11-15T10:47:51.7775781Z 
2024-11-15T10:47:51.7775856Z 
2024-11-15T10:47:51.7775928Z 
2024-11-15T10:47:51.7776000Z 
2024-11-15T10:47:52.0787565Z *** Import NAV/BC Management DLL's [False]
2024-11-15T10:47:52.0835982Z *** Loading assemblies for ServiceTier [BC].
2024-11-15T10:47:52.3229089Z *** Loading assemblies from: [C:\program files\microsoft dynamics nav\190\service]
2024-11-15T10:47:52.3805706Z *** BC Management DLL: C:\program files\microsoft dynamics nav\190\service\Microsoft.Dynamics.Nav.Management.dll
2024-11-15T10:47:52.3914827Z *** Selected module: [C:\program files\microsoft dynamics nav\190\service\Microsoft.Dynamics.Nav.Management.dll]
2024-11-15T10:47:52.3929805Z *** Loading module: [C:\program files\microsoft dynamics nav\190\service\Microsoft.Dynamics.Nav.Management.dll]
2024-11-15T10:47:52.5248479Z *** BC App Management DLL: C:\program files\microsoft dynamics nav\190\service\Microsoft.Dynamics.Nav.Apps.Management.dll
2024-11-15T10:47:52.5265332Z *** Selected module: [C:\program files\microsoft dynamics nav\190\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
2024-11-15T10:47:52.5277432Z *** Loading module: [C:\program files\microsoft dynamics nav\190\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
2024-11-15T10:47:52.5874344Z *** Setup VSIX for ALTOOL
2024-11-15T10:47:52.6029071Z *** ALTool Path: Not available
2024-11-15T10:47:52.6059742Z *** Using AL Compiler  located [C:\Run\Microsoft.al\al-\extension\bin\win32\alc.exe]
2024-11-15T10:47:52.6067780Z ***
2024-11-15T10:47:52.8116328Z *** Setting up AL Compiler [ALLanguage]
2024-11-15T10:47:52.9084978Z *** Downloading AL Compiler [ALLanguage]
2024-11-15T10:47:52.9193836Z *** Get Extension from Local-Disk...[C:\Run\ALLanguage.vsix]
2024-11-15T10:47:52.9207516Z *** Resolving Path [C:\Run\ALLanguage.vsix]
2024-11-15T10:47:53.2433887Z *** VSIX Path Resolved: [C:\Run\ALLanguage.vsix]
2024-11-15T10:47:53.2459084Z *** Unpacking Extension to folder...
2024-11-15T10:47:56.3111107Z *** ALTool Path: Not available
2024-11-15T10:47:56.3152443Z *** Using AL Compiler [vALLanguage] located [C:\Run\Microsoft.al\al-ALLanguage\extension\bin\win32\alc.exe]
2024-11-15T10:47:56.3164421Z ***
2024-11-15T10:47:56.3180750Z *** Working folder: C:\vsts-agent-alops-warp10\_work\2\s
2024-11-15T10:47:56.3191969Z ***
2024-11-15T10:47:56.3202907Z *** Copy Working folder to Docker Container: d4a583e5e33ed6a9fcc1f0d87be67834dc6d597ad2af451327955c935d416349
2024-11-15T10:47:56.3216222Z *** Docker Working Folder: c:\Run\DevOps\
2024-11-15T10:47:56.3225661Z *** Copy from [C:\vsts-agent-alops-warp10\_work\2\s] to [c:\Run\DevOps\]
2024-11-15T10:47:56.3269519Z *** Source File setup completed
2024-11-15T10:47:56.4197778Z *** Target Project: \app\app.json
2024-11-15T10:47:56.4213005Z *** Check for app.json files: c:\Run\DevOps\
2024-11-15T10:47:56.4333233Z *** Project found:
2024-11-15T10:47:56.4390099Z    - C:\Run\DevOps\app
2024-11-15T10:47:56.4421434Z *** Retrieving App-Info [\app\app.json]
2024-11-15T10:47:56.4536178Z *** Loading Json Object: [c:\Run\DevOps\app\app.json]
2024-11-15T10:47:56.4716402Z   * App.ID          = 30c110b4-f393-4fa2-b499-9bc8cd15e838
2024-11-15T10:47:56.4738264Z   * App.Name        = BC19
2024-11-15T10:47:56.4758296Z   * App.Publisher   = Duvel Moortgat nv
2024-11-15T10:47:56.4781239Z   * App.Version     = 3.0.1400.8
2024-11-15T10:47:56.4797844Z   * App.Platform    = 19.0.38062.0
2024-11-15T10:47:56.4817571Z   * App.Application = 19.0.29894.30693
2024-11-15T10:47:56.4874307Z *** Check Runtime: [8.0]
2024-11-15T10:47:56.4993913Z ***
2024-11-15T10:47:56.5564476Z *** Retaining original [Major] from version (?.0.0.0)
2024-11-15T10:47:56.5599096Z *** Retaining original [Minor] from version (0.?.0.0)
2024-11-15T10:47:56.5653201Z *** Setting Managed App Version [c:\Run\DevOps\app\app.json] =>  3.0.1406.0
2024-11-15T10:47:56.6006473Z *** Final app.json:
2024-11-15T10:47:56.6006738Z {
2024-11-15T10:47:56.6006989Z     "id":  "30c110b4-f393-4fa2-b499-9bc8cd15e838",
2024-11-15T10:47:56.6007253Z     "name":  "BC19",
2024-11-15T10:47:56.6007507Z     "publisher":  "Duvel Moortgat nv",
2024-11-15T10:47:56.6007764Z     "version":  "3.0.1406.0",
2024-11-15T10:47:56.6008005Z     "description":  "",
2024-11-15T10:47:56.6008239Z     "privacyStatement":  "",
2024-11-15T10:47:56.6008482Z     "EULA":  "",
2024-11-15T10:47:56.6008685Z     "help":  "",
2024-11-15T10:47:56.6009104Z     "url":  "",
2024-11-15T10:47:56.6009305Z     "logo":  "",
2024-11-15T10:47:56.6009516Z     "dependencies":  [
2024-11-15T10:47:56.6009727Z                          {
2024-11-15T10:47:56.6009993Z                              "id":  "e55908d7-0741-4ffd-ab42-10ad0fa3f028",
2024-11-15T10:47:56.6010298Z                              "name":  "Document Creator",
2024-11-15T10:47:56.6010573Z                              "publisher":  "Apportunix",
2024-11-15T10:47:56.6010835Z                              "version":  "1.44.1.0"
2024-11-15T10:47:56.6011068Z                          },
2024-11-15T10:47:56.6011271Z                          {
2024-11-15T10:47:56.6011541Z                              "id":  "f3e5b4ca-0ad8-4793-ba43-f52a38a8bee3",
2024-11-15T10:47:56.6011878Z                              "name":  "Continia Document Output OnPremise",
2024-11-15T10:47:56.6012189Z                              "publisher":  "Continia Software",
2024-11-15T10:47:56.6012577Z                              "version":  "2.0.2.0"
2024-11-15T10:47:56.6012809Z                          },
2024-11-15T10:47:56.6013008Z                          {
2024-11-15T10:47:56.6013273Z                              "id":  "f4b69b55-c90d-4937-8f53-2742898fa948",
2024-11-15T10:47:56.6013592Z                              "name":  "Continia Document Output",
2024-11-15T10:47:56.6013889Z                              "publisher":  "Continia Software",
2024-11-15T10:47:56.6014161Z                              "version":  "7.2.6.0"
2024-11-15T10:47:56.6014385Z                          },
2024-11-15T10:47:56.6014574Z                          {
2024-11-15T10:47:56.6014840Z                              "id":  "0745e76d-0b72-4641-87c2-ee45db5d2c32",
2024-11-15T10:47:56.6015156Z                              "name":  "Continia Delivery Network",
2024-11-15T10:47:56.6015450Z                              "publisher":  "Continia Software",
2024-11-15T10:47:56.6015738Z                              "version":  "4.2.1.137518"
2024-11-15T10:47:56.6015980Z                          },
2024-11-15T10:47:56.6016180Z                          {
2024-11-15T10:47:56.6016447Z                              "id":  "4b915d7e-c02a-435f-85ab-649086c1e002",
2024-11-15T10:47:56.6016757Z                              "name":  "Continia Core",
2024-11-15T10:47:56.6017037Z                              "publisher":  "Continia Software",
2024-11-15T10:47:56.6017320Z                              "version":  "7.1.0.95811"
2024-11-15T10:47:56.6017559Z                          }
2024-11-15T10:47:56.6017760Z                      ],
2024-11-15T10:47:56.6017974Z     "screenshots":  [
2024-11-15T10:47:56.6018076Z 
2024-11-15T10:47:56.6018265Z                     ],
2024-11-15T10:47:56.6018495Z     "platform":  "19.0.38062.0",
2024-11-15T10:47:56.6018768Z     "application":  "19.0.29894.30693",
2024-11-15T10:47:56.6019020Z     "idRanges":  [
2024-11-15T10:47:56.6019235Z                      {
2024-11-15T10:47:56.6019454Z                          "from":  50000,
2024-11-15T10:47:56.6019693Z                          "to":  50370
2024-11-15T10:47:56.6019908Z                      },
2024-11-15T10:47:56.6020100Z                      {
2024-11-15T10:47:56.6020316Z                          "from":  50376,
2024-11-15T10:47:56.6020547Z                          "to":  70000
2024-11-15T10:47:56.6020759Z                      },
2024-11-15T10:47:56.6020946Z                      {
2024-11-15T10:47:56.6021169Z                          "from":  80001,
2024-11-15T10:47:56.6021408Z                          "to":  90000
2024-11-15T10:47:56.6021634Z                      },
2024-11-15T10:47:56.6021837Z                      {
2024-11-15T10:47:56.6022054Z                          "from":  90001,
2024-11-15T10:47:56.6022284Z                          "to":  99999
2024-11-15T10:47:56.6022491Z                      }
2024-11-15T10:47:56.6022682Z                  ],
2024-11-15T10:47:56.6022950Z     "contextSensitiveHelpUrl":  "https://BC19.com/help/",
2024-11-15T10:47:56.6023339Z     "resourceExposurePolicy":  {
2024-11-15T10:47:56.6023611Z                                    "allowDebugging":  true,
2024-11-15T10:47:56.6023911Z                                    "allowDownloadingSource":  false,
2024-11-15T10:47:56.6024218Z                                    "includeSourceInSymbolFile":  false
2024-11-15T10:47:56.6024472Z                                },
2024-11-15T10:47:56.6024693Z     "runtime":  "8.0",
2024-11-15T10:47:56.6024927Z     "target":  "OnPrem",
2024-11-15T10:47:56.6025149Z     "features":  [
2024-11-15T10:47:56.6025370Z                      "TranslationFile"
2024-11-15T10:47:56.6025582Z                  ]
2024-11-15T10:47:56.6025763Z }
2024-11-15T10:47:56.6025838Z 
2024-11-15T10:47:56.6026014Z ***
2024-11-15T10:47:56.6345595Z *** Working Direcotry: [c:\Run\DevOps\]
2024-11-15T10:47:56.6356042Z *** Target Project: [\app\app.json]
2024-11-15T10:47:56.6364843Z *** Project Directory: [c:\Run\DevOps\app]
2024-11-15T10:47:56.6390460Z *** VSCode Settings: [c:\Run\DevOps\app\.vscode\settings.json]
2024-11-15T10:47:56.6414170Z *** VSCode-Settings json found.
2024-11-15T10:47:56.6421224Z *** Loading Json Object: [c:\Run\DevOps\app\.vscode\settings.json]
2024-11-15T10:47:56.6454024Z *** No AL-RuleSet json found.
2024-11-15T10:47:56.6463525Z ***
2024-11-15T10:47:56.7768549Z *** Resolve Docker Credentials
2024-11-15T10:47:56.7837198Z *** Setup BC Username/Password from Container info
2024-11-15T10:47:56.8223412Z *** Download Symbols
2024-11-15T10:47:57.0053569Z *** Working Dir: c:\Run\DevOps\
2024-11-15T10:47:57.0064797Z *** Load Code-Analysis from VSIX Folder
2024-11-15T10:47:57.0169998Z *** Loading assemblies from: [C:\Run\Microsoft.al\al-ALLanguage\extension\bin]
2024-11-15T10:47:57.0448325Z *** Loading: [C:\Run\Microsoft.al\al-ALLanguage\extension\bin\Microsoft.Dynamics.Nav.CodeAnalysis.dll]
2024-11-15T10:47:57.1608920Z *** PackageCache path created [c:\Run\DevOps\PackageCache]
2024-11-15T10:47:57.1622754Z ***
2024-11-15T10:47:57.1715620Z *** Propagated Dependency: Apportunix - Document Creator - 1.44.1.0
2024-11-15T10:47:57.1784588Z *** Propagated Dependency: Continia Software - Continia Document Output OnPremise - 2.0.2.0
2024-11-15T10:47:57.1805715Z *** Propagated Dependency: Continia Software - Continia Document Output - 7.2.6.0
2024-11-15T10:47:57.1823313Z *** Propagated Dependency: Continia Software - Continia Delivery Network - 4.2.1.137518
2024-11-15T10:47:57.1837866Z *** Propagated Dependency: Continia Software - Continia Core - 7.1.0.95811
2024-11-15T10:47:57.1850557Z *** Download System-Symbols for [19.0.38062.0]
2024-11-15T10:47:57.2342775Z *** Downloading NAV Symbols for [System v19.0.38062.0]
2024-11-15T10:47:57.2356658Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=19.0.38062.0&tenant=default]
2024-11-15T10:47:57.2741035Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:47:57.2767206Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=19.0.38062.0&tenant=default
2024-11-15T10:47:58.1889995Z *** Content-Disposition: attachment; filename=Microsoft_System_19.0.38062.0.app
2024-11-15T10:47:58.2064511Z *** Saving symbol file [Microsoft_System_19.0.38062.0.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:47:58.2393049Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Microsoft_System_19.0.38062.0.app].
2024-11-15T10:47:58.3054351Z ***
2024-11-15T10:47:58.3068246Z *** Download Application-Symbols for [19.0.29894.30693]
2024-11-15T10:47:58.3105498Z *** Downloading NAV Symbols for [Application v19.0.29894.30693]
2024-11-15T10:47:58.3114736Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=19.0.29894.30693&tenant=default]
2024-11-15T10:47:58.3123798Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:47:58.3132168Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=19.0.29894.30693&tenant=default
2024-11-15T10:47:58.6701088Z *** Content-Disposition: attachment; filename=Microsoft_Application_19.6.38118.0.app
2024-11-15T10:47:58.6722773Z *** Saving symbol file [Microsoft_Application_19.6.38118.0.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:47:58.6735126Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Microsoft_Application_19.6.38118.0.app].
2024-11-15T10:47:58.6939930Z *** Propagated Dependency: Microsoft - System Application - 19.6.0.0
2024-11-15T10:47:58.6994455Z *** Propagated Dependency: Microsoft - Base Application - 19.6.0.0
2024-11-15T10:47:58.7026480Z ***
2024-11-15T10:47:58.7064317Z *** Check for Depency Apps 7
2024-11-15T10:47:58.7117182Z *** Download Application-Symbols for [Document Creator v1.44.1.0]
2024-11-15T10:47:58.7142178Z *** Downloading NAV Symbols for [Document Creator v1.44.1.0]
2024-11-15T10:47:58.7159156Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Apportunix&appName=Document+Creator&versionText=1.44.1.0&tenant=default&appid=e55908d7-0741-4ffd-ab42-10ad0fa3f028]
2024-11-15T10:47:58.7176476Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:47:58.7186275Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Apportunix&appName=Document+Creator&versionText=1.44.1.0&tenant=default&appid=e55908d7-0741-4ffd-ab42-10ad0fa3f028
2024-11-15T10:47:59.1070561Z *** Content-Disposition: attachment; filename="Apportunix_Document Creator_1.44.1.0.app"
2024-11-15T10:47:59.1087952Z *** Saving symbol file [Apportunix_Document Creator_1.44.1.0.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:47:59.1117396Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Apportunix_Document Creator_1.44.1.0.app].
2024-11-15T10:47:59.1148018Z *** Propagated Dependency: Apportunix - System Library - 1.28.0.0
2024-11-15T10:47:59.1162396Z *** Propagated Dependency: Apportunix - Monet - 1.34.0.0
2024-11-15T10:47:59.1173974Z *** Propagated Dependency: Apportunix - PDF Merge - 1.2.0.0
2024-11-15T10:47:59.1196955Z *** Propagated Dependency: Microsoft - Application - 19.1.0.0
2024-11-15T10:47:59.1207935Z ***
2024-11-15T10:47:59.1228701Z *** Download Application-Symbols for [Continia Document Output OnPremise v2.0.2.0]
2024-11-15T10:47:59.1237715Z *** Downloading NAV Symbols for [Continia Document Output OnPremise v2.0.2.0]
2024-11-15T10:47:59.1247801Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Continia+Software&appName=Continia+Document+Output+OnPremise&versionText=2.0.2.0&tenant=default&appid=f3e5b4ca-0ad8-4793-ba43-f52a38a8bee3]
2024-11-15T10:47:59.1259733Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:47:59.1269121Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Continia+Software&appName=Continia+Document+Output+OnPremise&versionText=2.0.2.0&tenant=default&appid=f3e5b4ca-0ad8-4793-ba43-f52a38a8bee3
2024-11-15T10:47:59.4770722Z *** Content-Disposition: attachment; filename="Continia Software_Continia Document Output OnPremise_2.0.2.0.app"
2024-11-15T10:47:59.4789798Z *** Saving symbol file [Continia Software_Continia Document Output OnPremise_2.0.2.0.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:47:59.4818675Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Continia Software_Continia Document Output OnPremise_2.0.2.0.app].
2024-11-15T10:47:59.4886461Z *** Propagated Dependency: Continia Software - Continia Document Output - 7.2.0.0
2024-11-15T10:47:59.4945576Z *** Propagated Dependency: Microsoft - Application - 19.0.0.0
2024-11-15T10:47:59.5089089Z ***
2024-11-15T10:47:59.5102233Z *** Download Application-Symbols for [Continia Document Output v7.2.6.0]
2024-11-15T10:47:59.5110208Z *** Downloading NAV Symbols for [Continia Document Output v7.2.6.0]
2024-11-15T10:47:59.5123318Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Continia+Software&appName=Continia+Document+Output&versionText=7.2.6.0&tenant=default&appid=f4b69b55-c90d-4937-8f53-2742898fa948]
2024-11-15T10:47:59.5132887Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:47:59.5141877Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Continia+Software&appName=Continia+Document+Output&versionText=7.2.6.0&tenant=default&appid=f4b69b55-c90d-4937-8f53-2742898fa948
2024-11-15T10:47:59.9037257Z *** Content-Disposition: attachment; filename="Continia Software_Continia Document Output_7.2.6.0.app"
2024-11-15T10:47:59.9057757Z *** Saving symbol file [Continia Software_Continia Document Output_7.2.6.0.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:47:59.9200780Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Continia Software_Continia Document Output_7.2.6.0.app].
2024-11-15T10:47:59.9878750Z *** Propagated Dependency: Continia Software - Continia Core - 7.1.0.0
2024-11-15T10:47:59.9890020Z *** Propagated Dependency: Continia Software - Continia Delivery Network - 4.2.0.0
2024-11-15T10:47:59.9922117Z ***
2024-11-15T10:47:59.9933498Z *** Download Application-Symbols for [Continia Delivery Network v4.2.1.137518]
2024-11-15T10:47:59.9948703Z *** Downloading NAV Symbols for [Continia Delivery Network v4.2.1.137518]
2024-11-15T10:47:59.9956447Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Continia+Software&appName=Continia+Delivery+Network&versionText=4.2.1.137518&tenant=default&appid=0745e76d-0b72-4641-87c2-ee45db5d2c32]
2024-11-15T10:47:59.9968435Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:47:59.9980338Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Continia+Software&appName=Continia+Delivery+Network&versionText=4.2.1.137518&tenant=default&appid=0745e76d-0b72-4641-87c2-ee45db5d2c32
2024-11-15T10:48:00.3725549Z *** Content-Disposition: attachment; filename="Continia Software_Continia Delivery Network_4.2.1.137518.app"
2024-11-15T10:48:00.3749029Z *** Saving symbol file [Continia Software_Continia Delivery Network_4.2.1.137518.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:48:00.3802758Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Continia Software_Continia Delivery Network_4.2.1.137518.app].
2024-11-15T10:48:00.4110065Z ***
2024-11-15T10:48:00.4126289Z *** Download Application-Symbols for [Continia Core v7.1.0.95811]
2024-11-15T10:48:00.4138844Z *** Downloading NAV Symbols for [Continia Core v7.1.0.95811]
2024-11-15T10:48:00.4150003Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Continia+Software&appName=Continia+Core&versionText=7.1.0.95811&tenant=default&appid=4b915d7e-c02a-435f-85ab-649086c1e002]
2024-11-15T10:48:00.4165591Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:48:00.4177364Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Continia+Software&appName=Continia+Core&versionText=7.1.0.95811&tenant=default&appid=4b915d7e-c02a-435f-85ab-649086c1e002
2024-11-15T10:48:00.8136898Z *** Content-Disposition: attachment; filename="Continia Software_Continia Core_7.1.0.95811.app"
2024-11-15T10:48:00.8162435Z *** Saving symbol file [Continia Software_Continia Core_7.1.0.95811.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:48:00.8174812Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Continia Software_Continia Core_7.1.0.95811.app].
2024-11-15T10:48:00.8191958Z ***
2024-11-15T10:48:00.8242524Z *** Download Application-Symbols for [System Application v19.6.0.0]
2024-11-15T10:48:00.8293860Z *** Downloading NAV Symbols for [System Application v19.6.0.0]
2024-11-15T10:48:00.8303696Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Microsoft&appName=System+Application&versionText=19.6.0.0&tenant=default&appid=63ca2fa4-4f03-4f2b-a480-172fef340d3f]
2024-11-15T10:48:00.8315702Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:48:00.8321797Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Microsoft&appName=System+Application&versionText=19.6.0.0&tenant=default&appid=63ca2fa4-4f03-4f2b-a480-172fef340d3f
2024-11-15T10:48:01.1997586Z *** Content-Disposition: attachment; filename="Microsoft_System Application_19.6.38118.0.app"
2024-11-15T10:48:01.2030811Z *** Saving symbol file [Microsoft_System Application_19.6.38118.0.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:48:01.2132075Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Microsoft_System Application_19.6.38118.0.app].
2024-11-15T10:48:01.2241059Z ***
2024-11-15T10:48:01.2253371Z *** Download Application-Symbols for [Base Application v19.6.0.0]
2024-11-15T10:48:01.2268167Z *** Downloading NAV Symbols for [Base Application v19.6.0.0]
2024-11-15T10:48:01.2277436Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Microsoft&appName=Base+Application&versionText=19.6.0.0&tenant=default&appid=437dbf0e-84ff-417a-965d-ed2bb9650972]
2024-11-15T10:48:01.2290840Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:48:01.2299316Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Microsoft&appName=Base+Application&versionText=19.6.0.0&tenant=default&appid=437dbf0e-84ff-417a-965d-ed2bb9650972
2024-11-15T10:48:01.7123796Z *** Content-Disposition: attachment; filename="Microsoft_Base Application_19.6.38118.0.app"
2024-11-15T10:48:01.7143535Z *** Saving symbol file [Microsoft_Base Application_19.6.38118.0.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:48:01.9465496Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Microsoft_Base Application_19.6.38118.0.app].
2024-11-15T10:48:02.0362647Z ***
2024-11-15T10:48:02.0381123Z *** Download Application-Symbols for [System Library v1.28.0.0]
2024-11-15T10:48:02.0393556Z *** Downloading NAV Symbols for [System Library v1.28.0.0]
2024-11-15T10:48:02.0406545Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Apportunix&appName=System+Library&versionText=1.28.0.0&tenant=default&appid=b89eeffd-50f1-4628-950e-857a0ab9edca]
2024-11-15T10:48:02.0418914Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:48:02.0430057Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Apportunix&appName=System+Library&versionText=1.28.0.0&tenant=default&appid=b89eeffd-50f1-4628-950e-857a0ab9edca
2024-11-15T10:48:02.3994003Z *** Content-Disposition: attachment; filename="Apportunix_System Library_1.28.0.0.app"
2024-11-15T10:48:02.4021686Z *** Saving symbol file [Apportunix_System Library_1.28.0.0.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:48:02.4042877Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Apportunix_System Library_1.28.0.0.app].
2024-11-15T10:48:02.4064148Z ***
2024-11-15T10:48:02.4073674Z *** Download Application-Symbols for [Monet v1.34.0.0]
2024-11-15T10:48:02.4093828Z *** Downloading NAV Symbols for [Monet v1.34.0.0]
2024-11-15T10:48:02.4100014Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Apportunix&appName=Monet&versionText=1.34.0.0&tenant=default&appid=e0f70cf5-3004-4fd7-9ec0-0efe161a6f20]
2024-11-15T10:48:02.4115180Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:48:02.4125066Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Apportunix&appName=Monet&versionText=1.34.0.0&tenant=default&appid=e0f70cf5-3004-4fd7-9ec0-0efe161a6f20
2024-11-15T10:48:02.7721836Z *** Content-Disposition: attachment; filename=Apportunix_Monet_1.34.0.0.app
2024-11-15T10:48:02.7751751Z *** Saving symbol file [Apportunix_Monet_1.34.0.0.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:48:02.7764994Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Apportunix_Monet_1.34.0.0.app].
2024-11-15T10:48:02.7787366Z *** Propagated Dependency: Apportunix - System Library - 1.26.0.0
2024-11-15T10:48:02.7806760Z ***
2024-11-15T10:48:02.7824522Z *** Download Application-Symbols for [PDF Merge v1.2.0.0]
2024-11-15T10:48:02.7835893Z *** Downloading NAV Symbols for [PDF Merge v1.2.0.0]
2024-11-15T10:48:02.7845652Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Apportunix&appName=PDF+Merge&versionText=1.2.0.0&tenant=default&appid=aed24191-109d-4004-b0c2-760d3e3bc218]
2024-11-15T10:48:02.7870904Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:48:02.7880284Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Apportunix&appName=PDF+Merge&versionText=1.2.0.0&tenant=default&appid=aed24191-109d-4004-b0c2-760d3e3bc218
2024-11-15T10:48:03.1461181Z *** Content-Disposition: attachment; filename="Apportunix_PDF Merge_1.2.0.0.app"
2024-11-15T10:48:03.1483644Z *** Saving symbol file [Apportunix_PDF Merge_1.2.0.0.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:48:03.1500475Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Apportunix_PDF Merge_1.2.0.0.app].
2024-11-15T10:48:03.1522646Z *** Propagated Dependency: Apportunix - System Library - 1.20.0.0
2024-11-15T10:48:03.1728874Z *** Propagated Dependency: Apportunix - Monet - 1.32.0.0
2024-11-15T10:48:03.1746927Z ***
2024-11-15T10:48:03.1758066Z *** Download Application-Symbols for [Application v19.1.0.0]
2024-11-15T10:48:03.1773265Z *** Downloading NAV Symbols for [Application v19.1.0.0]
2024-11-15T10:48:03.1783816Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=19.1.0.0&tenant=default&appid=c1335042-3002-4257-bf8a-75c898ccb1b8]
2024-11-15T10:48:03.1795480Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:48:03.1804873Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=19.1.0.0&tenant=default&appid=c1335042-3002-4257-bf8a-75c898ccb1b8
2024-11-15T10:48:03.5294196Z *** Content-Disposition: attachment; filename=Microsoft_Application_19.6.38118.0.app
2024-11-15T10:48:03.5321310Z *** Saving symbol file [Microsoft_Application_19.6.38118.0.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:48:03.5335053Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Microsoft_Application_19.6.38118.0.app].
2024-11-15T10:48:03.5354863Z ***
2024-11-15T10:48:03.5371720Z *** Download Application-Symbols for [Continia Document Output v7.2.0.0]
2024-11-15T10:48:03.5383030Z *** Downloading NAV Symbols for [Continia Document Output v7.2.0.0]
2024-11-15T10:48:03.5389097Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Continia+Software&appName=Continia+Document+Output&versionText=7.2.0.0&tenant=default&appid=f4b69b55-c90d-4937-8f53-2742898fa948]
2024-11-15T10:48:03.5403092Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:48:03.5412698Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Continia+Software&appName=Continia+Document+Output&versionText=7.2.0.0&tenant=default&appid=f4b69b55-c90d-4937-8f53-2742898fa948
2024-11-15T10:48:03.9286501Z *** Content-Disposition: attachment; filename="Continia Software_Continia Document Output_7.2.6.0.app"
2024-11-15T10:48:03.9315004Z *** Saving symbol file [Continia Software_Continia Document Output_7.2.6.0.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:48:03.9415224Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Continia Software_Continia Document Output_7.2.6.0.app].
2024-11-15T10:48:04.0064396Z ***
2024-11-15T10:48:04.0080054Z *** Download Application-Symbols for [Application v19.0.0.0]
2024-11-15T10:48:04.0095590Z *** Downloading NAV Symbols for [Application v19.0.0.0]
2024-11-15T10:48:04.0105155Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=19.0.0.0&tenant=default&appid=c1335042-3002-4257-bf8a-75c898ccb1b8]
2024-11-15T10:48:04.0117877Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:48:04.0128434Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=19.0.0.0&tenant=default&appid=c1335042-3002-4257-bf8a-75c898ccb1b8
2024-11-15T10:48:04.3679389Z *** Content-Disposition: attachment; filename=Microsoft_Application_19.6.38118.0.app
2024-11-15T10:48:04.3702564Z *** Saving symbol file [Microsoft_Application_19.6.38118.0.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:48:04.3716295Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Microsoft_Application_19.6.38118.0.app].
2024-11-15T10:48:04.3747599Z ***
2024-11-15T10:48:04.3768641Z *** Download Application-Symbols for [Continia Core v7.1.0.0]
2024-11-15T10:48:04.3792962Z *** Downloading NAV Symbols for [Continia Core v7.1.0.0]
2024-11-15T10:48:04.3807413Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Continia+Software&appName=Continia+Core&versionText=7.1.0.0&tenant=default&appid=4b915d7e-c02a-435f-85ab-649086c1e002]
2024-11-15T10:48:04.3812096Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:48:04.3823063Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Continia+Software&appName=Continia+Core&versionText=7.1.0.0&tenant=default&appid=4b915d7e-c02a-435f-85ab-649086c1e002
2024-11-15T10:48:04.7487606Z *** Content-Disposition: attachment; filename="Continia Software_Continia Core_7.1.0.95811.app"
2024-11-15T10:48:04.7520998Z *** Saving symbol file [Continia Software_Continia Core_7.1.0.95811.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:48:04.7535845Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Continia Software_Continia Core_7.1.0.95811.app].
2024-11-15T10:48:04.7549165Z ***
2024-11-15T10:48:04.7567250Z *** Download Application-Symbols for [Continia Delivery Network v4.2.0.0]
2024-11-15T10:48:04.7576259Z *** Downloading NAV Symbols for [Continia Delivery Network v4.2.0.0]
2024-11-15T10:48:04.7585148Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Continia+Software&appName=Continia+Delivery+Network&versionText=4.2.0.0&tenant=default&appid=0745e76d-0b72-4641-87c2-ee45db5d2c32]
2024-11-15T10:48:04.7597517Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:48:04.7607174Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Continia+Software&appName=Continia+Delivery+Network&versionText=4.2.0.0&tenant=default&appid=0745e76d-0b72-4641-87c2-ee45db5d2c32
2024-11-15T10:48:05.2569389Z *** Content-Disposition: attachment; filename="Continia Software_Continia Delivery Network_4.2.1.137518.app"
2024-11-15T10:48:05.2587990Z *** Saving symbol file [Continia Software_Continia Delivery Network_4.2.1.137518.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:48:05.2626794Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Continia Software_Continia Delivery Network_4.2.1.137518.app].
2024-11-15T10:48:05.2950152Z ***
2024-11-15T10:48:05.2966417Z *** Download Application-Symbols for [System Library v1.26.0.0]
2024-11-15T10:48:05.2980366Z *** Downloading NAV Symbols for [System Library v1.26.0.0]
2024-11-15T10:48:05.2989834Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Apportunix&appName=System+Library&versionText=1.26.0.0&tenant=default&appid=b89eeffd-50f1-4628-950e-857a0ab9edca]
2024-11-15T10:48:05.2999498Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:48:05.3010128Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Apportunix&appName=System+Library&versionText=1.26.0.0&tenant=default&appid=b89eeffd-50f1-4628-950e-857a0ab9edca
2024-11-15T10:48:05.6513456Z *** Content-Disposition: attachment; filename="Apportunix_System Library_1.28.0.0.app"
2024-11-15T10:48:05.6531852Z *** Saving symbol file [Apportunix_System Library_1.28.0.0.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:48:05.6545892Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Apportunix_System Library_1.28.0.0.app].
2024-11-15T10:48:05.6565420Z ***
2024-11-15T10:48:05.6577603Z *** Download Application-Symbols for [System Library v1.20.0.0]
2024-11-15T10:48:05.6590012Z *** Downloading NAV Symbols for [System Library v1.20.0.0]
2024-11-15T10:48:05.6598735Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Apportunix&appName=System+Library&versionText=1.20.0.0&tenant=default&appid=b89eeffd-50f1-4628-950e-857a0ab9edca]
2024-11-15T10:48:05.6611553Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:48:05.6622101Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Apportunix&appName=System+Library&versionText=1.20.0.0&tenant=default&appid=b89eeffd-50f1-4628-950e-857a0ab9edca
2024-11-15T10:48:06.0146153Z *** Content-Disposition: attachment; filename="Apportunix_System Library_1.28.0.0.app"
2024-11-15T10:48:06.0163340Z *** Saving symbol file [Apportunix_System Library_1.28.0.0.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:48:06.0177970Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Apportunix_System Library_1.28.0.0.app].
2024-11-15T10:48:06.0193890Z ***
2024-11-15T10:48:06.0205722Z *** Download Application-Symbols for [Monet v1.32.0.0]
2024-11-15T10:48:06.0230763Z *** Downloading NAV Symbols for [Monet v1.32.0.0]
2024-11-15T10:48:06.0237347Z *** Downloading NAV Symbols from [https://d4a583e5e33e:7049/BC/dev/packages?publisher=Apportunix&appName=Monet&versionText=1.32.0.0&tenant=default&appid=e0f70cf5-3004-4fd7-9ec0-0efe161a6f20]
2024-11-15T10:48:06.0243514Z *** Downloading NAV Symbols with BasicAuthentication [admin]
2024-11-15T10:48:06.0250065Z ##[command]Invoke-RestMethod -Method Get -Uri https://d4a583e5e33e:7049/BC/dev/packages?publisher=Apportunix&appName=Monet&versionText=1.32.0.0&tenant=default&appid=e0f70cf5-3004-4fd7-9ec0-0efe161a6f20
2024-11-15T10:48:06.3750069Z *** Content-Disposition: attachment; filename=Apportunix_Monet_1.34.0.0.app
2024-11-15T10:48:06.3777832Z *** Saving symbol file [Apportunix_Monet_1.34.0.0.app] to [c:\Run\DevOps\PackageCache]
2024-11-15T10:48:06.3791206Z *** Read App Manifest: [c:\Run\DevOps\PackageCache\Apportunix_Monet_1.34.0.0.app].
2024-11-15T10:48:06.3809443Z ***
2024-11-15T10:48:06.4477843Z *** Starting AL Compiler...
2024-11-15T10:48:06.4487951Z *** App.Name         = BC19
2024-11-15T10:48:06.4499236Z *** App.Publisher    = Duvel Moortgat nv
2024-11-15T10:48:06.4513326Z *** App.Compiler Path= C:\Run\Microsoft.al\al-ALLanguage\extension\bin\win32\alc.exe
2024-11-15T10:48:06.4570472Z *** Checking for Assemblies in App
2024-11-15T10:48:06.4835712Z *** Assemblies in App found. Adding Probing Paths (1).
2024-11-15T10:48:06.4849190Z   * C:\Run\DevOps\app\.netpackages
2024-11-15T10:48:06.4863540Z *** Add Windows Assembly Path [C:\Windows\assembly]
2024-11-15T10:48:06.5050624Z *** Detect ALC.EXE Features.
2024-11-15T10:48:06.5065341Z ##[command]& C:\Run\Microsoft.al\al-ALLanguage\extension\bin\win32\alc.exe /?
2024-11-15T10:48:06.6711254Z   * PARALLEL+
2024-11-15T10:48:06.6719194Z   * MAXDEGREEOFPARALLELISM
2024-11-15T10:48:06.6729349Z   * ASSEMBLYPROBINGPATHS
2024-11-15T10:48:06.6778033Z ##[command]& C:\Run\Microsoft.al\al-ALLanguage\extension\bin\win32\alc.exe /packagecachepath:"c:\Run\DevOps\PackageCache" /project:"c:\Run\DevOps\app" /out:"c:\Run\DevOps\Duvel Moortgat nv_BC19_3.0.1406.0_APP.app" /fullpaths /parallel+ /maxDegreeOfParallelism:2 /assemblyprobingpaths:"C:\Run\DevOps\app\.netpackages","C:\Windows\assembly","C:\Windows\Microsoft.NET\assembly","C:\Program Files\Microsoft Dynamics NAV\190\Service\Add-ins","C:\program files\microsoft dynamics nav\190\service"
2024-11-15T10:48:08.5654900Z *** AL Compiler Exit Code: -1
2024-11-15T10:48:08.5672305Z *** Full Compile Log:
2024-11-15T10:48:08.5724899Z Microsoft (R) AL Compiler version 8.4.9.9671 Copyright (C) Microsoft Corporation. All rights reserved  Compilation started for project 'BC19' containing '1921' files at '11:48:06.857'.   Compilation ended at '11:48:08.527'.  System.IO.IOException: There is not enough space on the disk. : 'C:\Windows\Microsoft.NET\assembly\GAC_MSIL\Microsoft.IIS.PowerShell.Framework.Resources\v4.0_10.0.0.0_en_31bf3856ad364e35'    at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath)    at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)    at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)    at Microsoft.Dynamics.Nav.CodeAnalysis.Utilities.DotNetUtilities.GetMsCorLibSearchPaths() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Utilities\DotNetUtilities.cs:line 114    at Microsoft.Dynamics.Nav.CodeAnalysis.DotNet.AssemblyLocator.GetProbingPaths(IEnumerable`1 probingPaths) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DotNet\AssemblyLocator.cs:line 37    at Microsoft.Dynamics.Nav.CodeAnalysis.DotNet.AssemblyLocator..ctor(IEnumerable`1 probingPaths, IReadOnlyDictionary`2 wellKnownAssemblies) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DotNet\AssemblyLocator.cs:line 22    at Microsoft.Dynamics.Nav.CodeAnalysis.DotNet.DotNetResolverFactoryHelper.CreateLocalDotNetResolverFactory(IReadOnlyList`1 assemblyProbingPaths) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DotNet\DotNetResolverFactoryHelper.cs:line 13    at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.NavCompiler.GetDotNetResolverFactory() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\NavCompiler.cs:line 126    at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.NavCompiler.GetOrCreateCompilation(CompilerTextWriter consoleOutput, CompilationOptions compilationOptions, ErrorLogger errorLogger) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\NavCompiler.cs:line 100    at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 450    at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 333    at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.Alc.<>c__DisplayClass1_0.<Run>b__0(CompilerTextWriter textWriterOut, CompilerTextWriter _) in D:\a\1\s\source\Prod\alc\Alc.cs:line 37    at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.ConsoleUtil.RunWithOutput[T](Boolean useUtf8Encoding, Func`3 func) in D:\a\1\s\source\Prod\alc\ConsoleUtil.cs:line 25    at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.Alc.Run(String clientDirectory, String baseDirectory, String[] args, IAnalyzerAssemblyLoader analyzerLoader) in D:\a\1\s\source\Prod\alc\Alc.cs:line 37
2024-11-15T10:48:08.5730759Z 
2024-11-15T10:48:08.9901867Z ##[error]Could not load file or assembly 'System.Dynamic, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. There is not enough space on the disk. (Exception from HRESULT: 0x80070070)
2024-11-15T10:48:09.0166854Z ##[section]Async Command Start: Add Build Tag
2024-11-15T10:48:09.0167825Z Build '1406' has following tags now: BC.Platform.19.0.38062.0, BC.Version.19.6.38118.0, AL.Compiler.ALLanguage, App.Document Creator.1.44.1.0, App.System Library.1.28.0.0, App.Monet.1.34.0.0, App.PDF Merge.1.2.0.0, App.Document Creator On-Premise.1.40.0.0, App.Continia Core.7.1.0.95811, App.Continia Delivery Network.4.2.1.137518, App.Continia Document Output.7.2.6.0, App.Continia Document Output OnPremise.2.0.2.0, myimage-onprem-19.6.38118.0-be-ltsc2019
2024-11-15T10:48:09.0168752Z ##[section]Async Command End: Add Build Tag
2024-11-15T10:48:09.0169480Z ##[section]Async Command Start: Update Build Number
2024-11-15T10:48:09.0169838Z Update build number to 3.0.1406.0 for build 1406
2024-11-15T10:48:09.0170072Z ##[section]Async Command End: Update Build Number
2024-11-15T10:48:09.0170896Z ##[section]Finishing: ALOps - Compile Extension: App
```

**Screenshots**
![image](https://github.com/user-attachments/assets/22852a4b-c865-4f23-9aae-769ee2ee6753)

**Comment by waldo1001** [comment]
I see that ALopsAppMaintenance is skipped when you have errors.  This should not be skipped, or you risk disks to get full (no maintenance).

Change your pipeline to always run the maintenance - it will clean up your disk.

```yaml
- task: ALOpsAgentMaintenance@1
  displayName: 'ALOps Agent Maintenance'
  condition: always()
  inputs:
    removeoldtasks: true
    removeunusedcontainers: '${{ parameters.removeunusedcontainers }}'
    pruneimagesdayscreated: '30'
    removebcartifacts: true
    daysunused: 14

- task: ALOpsDockerRemove@1
  displayName: 'Remove Docker Container'
  enabled: true
  condition: always()
  inputs:
    createeventlogbackup: onfailure

```

**Comment by ThomasWat** [comment]
ok, I adjusted the pipeline settings and ran a couple of times.
I'm still getting the same error: 
Exception calling "ExtractToDirectory" with "2" argument(s): "There is not enough space on the disk.

The maintenance step was not skipped this time:
![image](https://github.com/user-attachments/assets/1153e277-f7ce-4a9d-b957-cbbf03809716)

I removed the 'createeventlogbackup' because this was also giving me error with the saving the file.

**the updated yaml**
```yaml
#name: $(Build.BuildId)
name: ERP_BC_Build

trigger:
  branches:
    include:
      - 05.Test/Test
      - 04.Development/Development
      - 01.Main/Main

variables:
- group: 'BuildVariables'  # link to a variable group that has secret variables, like URL to license file, or sasToken for insider builds
- name: AppVersion
  value: ?.?.*.0
- name: BCVersion
  value: 19.6
- name: bc.license
  value: "$(System.DefaultWorkingDirectory)/.license/5118527.bclicense"

pool: ALOps

steps:
- checkout: self
  clean: true 

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/.apps'
    ArtifactName: 'DependentApps'
    publishLocation: 'Container'

- task: ALOpsDockerCreate@1
  displayName: 'ALOps - Create Docker Image if necessary' # It will reuse the image if already exists, or build one if it doesn't.
  inputs:
    artifacttype: OnPrem
    artifactversion: $(BCVersion)
    artifactcountry: be
    licensefile: '$(bc.license)'

- task: ALOpsDockerStart@1
  displayName: 'ALOps - Start Docker Container' # No need to provide any details - it will get the details from previous step
  inputs:
    docker_pull: false
    enable_api_services: true
    docker_parameters: | 
      --env customNavSettings=EnableTaskScheduler=false

- task: ALOpsDockerWait@1
  displayName: 'ALOps - Wait for Docker Container to start'
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  displayName: 'ALOps - Update License'
  inputs:
    usedocker: true
    license_path: '$(System.DefaultWorkingDirectory)/.license/5118527.bclicense'
    print_license_info: true

- task: ALOpsAppPublish@1
  displayName: 'ALOps - Install Dependent Apps'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    batch_publish_folder: '.apps'

- task: ALOpsAppCompiler@1
  displayName: 'ALOps - Compile Extension: App'
  inputs:
    usedocker: true
    nav_app_version: $(AppVersion)                          # ? = Take digit from the app.json, * = buildnumber
    targetproject: 'app/app.json'                           # The App
    failed_on_warnings: false
    app_file_suffix: '_APP'                                 # A trick to uniquely identify the APP (from the TEST-app)

- task: ALOpsAppPublish@1
  displayName: 'ALOps - Publish Extension'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    skip_verification: true

- task: ALOpsOpenAPI@1
  inputs:
    usedocker: true
    api_endpoint: 'https://$(ALOPS_DOCKER_HOSTNAME):7048/bc/api'
    authentication: 'basic'
    username: '$(ALOPS_DOCKER_ADMINUSER)'
    password: '$(ALOPS_DOCKER_ADMINPASSWORD)'
    export_yaml: true
    export_edmx: true
    discover: true
    publish_artifacts: true
    api_exclude_routes: |
        beta
        v1.0
    api_routes: |
        hodor/purchase/v1.0
    inspect_paths: true

- task: ALOpsInfo@1

- task: ALOpsAgentMaintenance@1
  displayName: 'ALOps Agent Maintenance'
  condition: always()
  inputs:
    removeoldtasks: true
    removeunusedcontainers: true
    pruneimagesdayscreated: 0
    removebcartifacts: true
    daysunused: 1

- task: ALOpsDockerRemove@1
  displayName: 'Remove Docker Container'
  enabled: true
  condition: always()
```

**Comment by waldo1001** [comment]
We upgraded your agent.  Should be solved now!
Please leave the maintenance-step in each pipeline ;-).

**Comment by ThomasWat** [comment]
Hi Waldo

Thanks for the answers but maybe I'm doing something wrong but I'm still getting the same error:
##[error]Exception calling "ExtractToDirectory" with "2" argument(s): "There is not enough space on the disk.

![image](https://github.com/user-attachments/assets/e0d2d0c9-ccc8-45c7-8fcc-0bdfc42eef85)

**the updated yaml**
```yaml
#name: $(Build.BuildId)
name: ERP_BC_Build

trigger:
  branches:
    include:
      - 05.Test/Test
      - 04.Development/Development
      - 01.Main/Main

variables:
- group: 'BuildVariables'  # link to a variable group that has secret variables, like URL to license file, or sasToken for insider builds
- name: AppVersion
  value: ?.?.*.0
- name: BCVersion
  value: 19.6
- name: bc.license
  value: "$(System.DefaultWorkingDirectory)/.license/5118527.bclicense"

pool: ALOps

steps:
- checkout: self
  clean: true 

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/.apps'
    ArtifactName: 'DependentApps'
    publishLocation: 'Container'

- task: ALOpsDockerCreate@1
  displayName: 'ALOps - Create Docker Image if necessary' # It will reuse the image if already exists, or build one if it doesn't.
  inputs:
    artifacttype: OnPrem
    artifactversion: $(BCVersion)
    artifactcountry: be
    licensefile: '$(bc.license)'

- task: ALOpsDockerStart@1
  displayName: 'ALOps - Start Docker Container' # No need to provide any details - it will get the details from previous step
  inputs:
    docker_pull: false
    enable_api_services: true
    docker_parameters: | 
      --env customNavSettings=EnableTaskScheduler=false

- task: ALOpsDockerWait@1
  displayName: 'ALOps - Wait for Docker Container to start'
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  displayName: 'ALOps - Update License'
  inputs:
    usedocker: true
    license_path: '$(System.DefaultWorkingDirectory)/.license/5118527.bclicense'
    print_license_info: true

- task: ALOpsAppPublish@1
  displayName: 'ALOps - Install Dependent Apps'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    batch_publish_folder: '.apps'

- task: ALOpsAppCompiler@1
  displayName: 'ALOps - Compile Extension: App'
  inputs:
    usedocker: true
    nav_app_version: $(AppVersion)                          # ? = Take digit from the app.json, * = buildnumber
    targetproject: 'app/app.json'                           # The App
    failed_on_warnings: false
    app_file_suffix: '_APP'                                 # A trick to uniquely identify the APP (from the TEST-app)

- task: ALOpsAppPublish@1
  displayName: 'ALOps - Publish Extension'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    skip_verification: true

- task: ALOpsOpenAPI@1
  inputs:
    usedocker: true
    api_endpoint: 'https://$(ALOPS_DOCKER_HOSTNAME):7048/bc/api'
    authentication: 'basic'
    username: '$(ALOPS_DOCKER_ADMINUSER)'
    password: '$(ALOPS_DOCKER_ADMINPASSWORD)'
    export_yaml: true
    export_edmx: true
    discover: true
    publish_artifacts: true
    api_exclude_routes: |
        beta
        v1.0
    api_routes: |
        hodor/purchase/v1.0
    inspect_paths: true

- task: ALOpsInfo@1

- task: ALOpsAgentMaintenance@1
  displayName: 'ALOps Agent Maintenance'
  condition: always()
  inputs:
    removeoldtasks: true
    removeunusedcontainers: true
    pruneimagesdayscreated: '30'
    removebcartifacts: true
    daysunused: 14

- task: ALOpsDockerRemove@1
  displayName: 'Remove Docker Container'
  enabled: true
  condition: always()
  inputs:
    createeventlogbackup: onfailure
```

**Comment by waldo1001** [comment]
We restarted, and the ghost containers are gone.

please report back

**Comment by ThomasWat** [comment]
Yes, that did the job!
Thanks for the help.
